### ISSUE TITLE
希望可以加入录制视频的REST API功能， 像WOWZA那样。

### ISSUE THREAD

**Issue by Thunder-Yan** [winlinvip/simple-rtmp-server#125]
希望winlinvip可以加入录制视频的REST API功能， 像WOWZA那样。
例如：开始录制视频
http://username:password@[wowza-address]:8086/livestreamrecord?app=live&streamname=myStream&action=stopRecording&version=false&output=/usr/local/WowzaMediaServer/content/c.mp4&fromat=mp4
app + streamname 定位一个具体的流
action  指定一个动作
output 指定一个输出路径(包含文件名)
format 指定输出的格式

**Comment by winlinvip** [comment]
因为改动很大，推迟到3.0.

**Comment by winlinvip** [comment]
参考 #319 ，需要实现了这个#319之后才能实现这个。
