### ISSUE TITLE
日志经常报一些HLS aac resync，是不是有什么问题

### ISSUE THREAD

**Issue by Benqing** [winlinvip/simple-rtmp-server#152]
174:^@[2014-08-15 13:03:36.682][trace][19055][121] dvr stream __defaultVhost__/is_live/10281-1 to file ./objs/nginx/html/is_live/10281-1.1408079016597.flv
257:^@[2014-08-15 13:03:52.727][trace][19055][121] <- WPB time=21343, okbps=1,0,0, ikbps=714,0,0
295:^@[2014-08-15 13:04:01.524][trace][19055][121] HLS aac resync, dpts=11493, pts=2721960, base=0, nb_samples=654, sample_rate=22050
299:^@[2014-08-15 13:04:02.323][trace][19055][121] HLS aac resync, dpts=11591, pts=2793960, base=2721960, nb_samples=20, sample_rate=22050
303:^@[2014-08-15 13:04:03.123][trace][19055][121] HLS aac resync, dpts=11591, pts=2865960, base=2793960, nb_samples=20, sample_rate=22050
306:^@[2014-08-15 13:04:03.723][trace][19055][121] HLS aac resync, dpts=10432, pts=2930760, base=2865960, nb_samples=18, sample_rate=22050
311:^@[2014-08-15 13:04:04.523][trace][19055][121] HLS aac resync, dpts=11591, pts=3002760, base=2930760, nb_samples=20, sample_rate=22050
313:^@[2014-08-15 13:04:04.723][trace][19055][121] -> HLS time=33261, stream dts=3012660(33474ms), sequence_no=12
318:^@[2014-08-15 13:04:05.342][trace][19055][121] HLS aac resync, dpts=11591, pts=3074760, base=3002760, nb_samples=20, sample_rate=22050
322:^@[2014-08-15 13:04:06.144][trace][19055][121] HLS aac resync, dpts=11591, pts=3146760, base=3074760, nb_samples=20, sample_rate=22050
325:^@[2014-08-15 13:04:06.544][trace][19055][121] dvr stream __defaultVhost__/is_live/10281-1 to file ./objs/nginx/html/is_live/10281-1.1408079046350.flv
334:^@[2014-08-15 13:04:06.924][trace][19055][121] HLS aac resync, dpts=9853, pts=3207960, base=3146760, nb_samples=17, sample_rate=22050
338:^@[2014-08-15 13:04:07.725][trace][19055][121] HLS aac resync, dpts=11591, pts=3279960, base=3207960, nb_samples=20, sample_rate=22050
343:^@[2014-08-15 13:04:08.547][trace][19055][121] HLS aac resync, dpts=11591, pts=3351960, base=3279960, nb_samples=20, sample_rate=22050
347:^@[2014-08-15 13:04:09.328][trace][19055][121] HLS aac resync, dpts=11591, pts=3423960, base=3351960, nb_samples=20, sample_rate=22050
352:^@[2014-08-15 13:04:09.948][trace][19055][121] HLS aac resync, dpts=10432, pts=3488760, base=3423960, nb_samples=18, sample_rate=22050
356:^@[2014-08-15 13:04:10.730][trace][19055][121] HLS aac resync, dpts=11591, pts=3560760, base=3488760, nb_samples=20, sample_rate=22050
361:^@[2014-08-15 13:04:11.551][trace][19055][121] HLS aac resync, dpts=11591, pts=3632760, base=3560760, nb_samples=20, sample_rate=22050
365:^@[2014-08-15 13:04:12.352][trace][19055][121] HLS aac resync, dpts=11591, pts=3704760, base=3632760, nb_samples=20, sample_rate=22050
368:^@[2014-08-15 13:04:13.133][trace][19055][121] HLS aac resync, dpts=9853, pts=3765960, base=3704760, nb_samples=17, sample_rate=22050
398:^@[2014-08-15 13:04:19.743][trace][19055][121] HLS aac resync, dpts=-13037, pts=4359960, base=3765960, nb_samples=139, sample_rate=22050
401:^@[2014-08-15 13:04:20.144][trace][19055][121] HLS aac resync, dpts=-15985, pts=4417740, base=4359960, nb_samples=10, sample_rate=22050
402:^@[2014-08-15 13:04:20.344][trace][19055][121] HLS aac resync, dpts=-9933, pts=4452750, base=4417740, nb_samples=6, sample_rate=22050
404:^@[2014-08-15 13:04:20.564][trace][19055][121] HLS aac resync, dpts=-11542, pts=4481010, base=4452750, nb_samples=4, sample_rate=22050
407:^@[2014-08-15 13:04:20.964][trace][19055][121] HLS aac resync, dpts=-18775, pts=4541580, base=4481010, nb_samples=10, sample_rate=22050
409:^@[2014-08-15 13:04:21.164][trace][19055][121] HLS aac resync, dpts=-10203, pts=4576860, base=4541580, nb_samples=6, sample_rate=22050
410:^@[2014-08-15 13:04:21.364][trace][19055][121] HLS aac resync, dpts=-10642, pts=4604220, base=4576860, nb_samples=4, sample_rate=22050
413:^@[2014-08-15 13:04:21.764][trace][19055][121] HLS aac resync, dpts=-17335, pts=4663350, base=4604220, nb_samples=10, sample_rate=22050
415:^@[2014-08-15 13:04:22.164][trace][19055][121] HLS aac resync, dpts=-17605, pts=4722750, base=4663350, nb_samples=10, sample_rate=22050
418:^@[2014-08-15 13:04:22.364][trace][19055][121] HLS aac resync, dpts=-9483, pts=4757310, base=4722750, nb_samples=6, sample_rate=22050
419:^@[2014-08-15 13:04:22.564][trace][19055][121] HLS aac resync, dpts=-10012, pts=4784040, base=4757310, nb_samples=4, sample_rate=22050
420:^@[2014-08-15 13:04:22.765][trace][19055][121] HLS aac resync, dpts=-16503, pts=4825620, base=4784040, nb_samples=6, sample_rate=22050

**Comment by winlinvip** [comment]
已经使用新的HLS算法组合Audio包，不再有这个问题了。
