### ISSUE TITLE
SRS log输出会把字符串的\0也打印到LOG文件里。

### ISSUE THREAD

**Issue by acikee** [winlinvip/simple-rtmp-server#207]
使用 od -c查看
0000000  \0   [   2   0   1   4   -   1   1   -   1   7       1   4   :
0000020   4   8   :   3   9   .   8   6   2   ]   [   t   r   a   c   e
0000040   ]   [   1   2   7   1   ]   [   1   1   4   5   0   7   ]
0000060   s   t   a   r   t       f   o   r   w   a   r   d       r   t
0000100   m   p   :   /   /   1   9   2   .   1   6   8   .   1   4   .
0000120   5   4   :   1   9   3   5   ?   v   h   o   s   t   =   _   _
0000140   d   e   f   a   u   l   t   V   h   o   s   t   _   _       t
0000160   o       r   t   m   p   :   /   /   1   9   2   .   1   6   8
0000200   .   1   4   .   5   4   :   1   9   3   6   :   1   9   3   6
0000220   ?   v   h   o   s   t   =   _   _   d   e   f   a   u   l   t
0000240   V   h   o   s   t   _   _   ,       t   c   U   r   l   =   r
0000260   t   m   p   :   /   /   1   9   2   .   1   6   8   .   1   4
0000300   .   5   4   :   1   9   3   6   /   l   i   v   e   ,       s
0000320   t   r   e   a   m   =   1   0   2  \n  \0

**Comment by tufang14** [comment]
认领

**Comment by winlinvip** [comment]
Zan~

**Comment by tufang14** [comment]
刚提交的版本错了，提交到master分支了，我重新提交个1.0的

**Comment by winlinvip** [comment]
OK

**Comment by winlinvip** [comment]
我合并到1.0release吧，大家提交到master就可以。我看哪些需要合并再合并过去。

**Comment by winlinvip** [comment]
O....
是应该提交到develop，没事，我来弄吧

**Comment by winlinvip** [comment]
是我弄错了，这次就提交到master吧，我已经合并到1.0release和develop两个分支了。
实际上1.0release是1.0的分支，一些hotfix都提交到这个地方。
而master是稳定分支，较多hotifx形成service pack之后发布。
develop是开发版。
