### ISSUE TITLE
视频源RTMP推流停止后，对应的HLS文件m3u8、ts能否清理掉？

### ISSUE THREAD

**Issue by walkermi** [winlinvip/simple-rtmp-server#209]
不知道目前SRS有没有这样的机制，当视频源RTMP停止推流后，将对应的m3u8、ts文件清理掉？

我现在的测试环境，源停止后，打开HLS仍然会播放缓存的ts文件，这样会给使用者困惑：图像上有OSD还好，可以知道是以前的图像；没有的就不太容易分辨。

不知道这个要求是否合理？

**Comment by hx227** [comment]
不清理也没关系，关键是重新推流后一直在写一个文件，不会循环生成新的ts文件了，详见#280

**Comment by winlinvip** [comment]
参考这个：#321 ，若记录了这些信息，是可以清理的。

**Comment by winlinvip** [comment]
#209 可以在系统重启时清理这些ts片，不过不好实现，若需要接着切片，那么就要保留。所以只能是等待一定时间，如果还没有流上来就清理掉，但这个就麻烦了。

综述，不清理。
