### ISSUE TITLE
vlc播放hls数据存在问题

### ISSUE THREAD

**Issue by yangyijie88** [winlinvip/simple-rtmp-server#214]
使用ble推送上来的屏幕数据，采用ffmpeg进行切片，没有问题，但srs进行切片处理的数据，vlc播放时会报如下错误：
[h264 @ 0x7fea24004e00] slice type too large (2) at 0 0
[h264 @ 0x7fea24004e00] decode_slice_header error
[h264 @ 0x7fea24004e00] no frame!
Non-reference picture received and no reference available
[h264 @ 0x7fea24004e00] decode_slice_header error
[h264 @ 0x7fea24004e00] slice type too large (2) at 0 0
[h264 @ 0x7fea24004e00] decode_slice_header error
[h264 @ 0x7fea24004e00] no frame!
[h264 @ 0x7fea24004e00] slice type too large (2) at 0 0
[h264 @ 0x7fea24004e00] decode_slice_header error
[h264 @ 0x7fea24004e00] no frame!
[h264 @ 0x7fea24004e00] no frame!
[h264 @ 0x7fea24004e00] no frame!
[00007fea240057b8] ts demux error: libdvbpsi (PSI decoder): TS duplicate (received 0, expected 1) for PID 0
[00007fea240057b8] ts demux error: libdvbpsi (PSI decoder): TS duplicate (received 0, expected 1) for PID 4097
[00007fea240057b8] ts demux error: libdvbpsi (PSI decoder): TS duplicate (received 0, expected 1) for PID 0
[00007fea240057b8] ts demux error: libdvbpsi (PSI decoder): TS duplicate (received 0, expected 1) for PID 4097
[h264 @ 0x7fea24004e00] slice type too large (2) at 0 0
[h264 @ 0x7fea24004e00] decode_slice_header error
[h264 @ 0x7fea24004e00] no frame!
[h264 @ 0x7fea24004e00] no frame!
[h264 @ 0x7fea24004e00] slice type too large (2) at 0 0
[h264 @ 0x7fea24004e00] decode_slice_header error
[h264 @ 0x7fea24004e00] no frame!
vlc还是可以播放的，uc也可以，但花屏都很严重。而且生成的ts文件的idr帧不是ts中视频数据的第一帧，因此会造成做hls的seek时花屏很严重。

**Comment by winlinvip** [comment]
哦，这个问题实际上是你改过后出现的问题吧？现在是为何close这个bug，解决了，还是支持这个功能了？

**Comment by yangyijie88** [comment]
我加了一点代码，每隔一定的帧插入一次pcr，数据可以正常播放，winlin大神可以参考一下哈。今天我本来想把它提交到develop中，刚发现在develop版本中却是不行的。还有avc_demux_ibmf_format的问题，我发现新的代码中已经改掉了，跟我上面写的效果是一样的。我就close了。

**Comment by yangyijie88** [comment]
不过在master版本中改动pcr的代码后，数据可以正常播放。我的分支里提交了。

**Comment by winlinvip** [comment]
额，develop是没有这个问题了么？develop是哪段代码完成了这个功能？

**Comment by yangyijie88** [comment]
pcr的问题，是我自己写了一点点代码，我发现ffmpeg中的ts数据，每隔2个帧，就会发送一个pcr而不是一定要等到frame->key为true。因此srs_app_hls.cpp中我改了这一点点,。还有在master中的srs_app_avc_aac.cpp的video_avc_demux函数跟develop中已经不一样啦。
develop版本：
if (avc_extra_size <= 0 || !avc_extra_data) {
            ret = ERROR_HLS_DECODE_ERROR;
            srs_error("hls decode video avc failed, sequence header not found. ret=%d", ret);
            return ret;
        }
        
        // One or more NALUs (Full frames are required)
        // try  "AnnexB" from H.264-AVC-ISO_IEC_14496-10.pdf, page 211.
        if ((ret = avc_demux_annexb_format(stream, sample)) != ERROR_SUCCESS) {
            // stop try when system error.
            if (ret != ERROR_HLS_AVC_TRY_OTHERS) {
                srs_error("avc demux for annexb failed. ret=%d", ret);
                return ret;
            }
            
            // try "ISO Base Media File Format" from H.264-AVC-ISO_IEC_14496-15.pdf, page 20
            if ((ret = avc_demux_ibmf_format(stream, sample)) != ERROR_SUCCESS) {
                return ret;
            }
        }
    } else {
        // ignored.
    }
感觉这里有点问题的。master中应是修改好的了。

**Comment by winlinvip** [comment]
HLS并不需要以IDR帧开头, PB帧开头也可以的, mac上没有看到严重的花屏.

**Comment by yangyijie88** [comment]
好的，谢谢提醒。最近没登陆。。
