### ISSUE TITLE
得到某个范围内的stream名

### ISSUE THREAD

**Issue by fgjun** [winlinvip/simple-rtmp-server#227]
可以得到整个srs或某个vhost或某个app范围内的stream吗？通过http callback还是什么接口可以直接返回?

**Comment by winlinvip** [comment]
跪求大侠们把这bug认领了吧。
我就可以直接开始干SRS3.0了。

**Comment by tufang14** [comment]
认领，我先弄个试试

**Comment by winlinvip** [comment]
HTTP-api算一个大功能了。
加油，弄完就可以和杰哥位列authors了。
杰哥当初提供的是带宽测速。
