### ISSUE TITLE
建议增加录制接口，用户请求srs录制某条直播流，参数app，stream，vhost由用户传过来

### ISSUE THREAD

**Issue by fgjun** [winlinvip/simple-rtmp-server#232]
建议增加接受用户【开始录制/停止录制】请求的http接口，用户请求srs录制某条直播流，参数app，stream，vhost由用户传过来，srs接受后可以返回json数据给客户端，原因如下：
1、客户端触发录制需求，比较好，服务器通过dvr配置或回调接口，这个还是不够灵活。
2、用户在直播现场调试设备、会议中途休息时间等，也会被录制，正常是只录会议进行时的视频，这些无效数据，增加服务器存储空负担

**Comment by walkermi** [comment]
期待这个功能，我记得作者实现了这个功能的部分，但为什么又revert掉了？什么时候会继续fix这个问题？

**Comment by winlinvip** [comment]
这个实现过于复杂，SRS2的功能加得太多了，我的时间有限，不能做好的功能只能暂时不做，等时间充裕了再好好做。
