### ISSUE TITLE
Publish by MPEG-TS over UDP to SRS.

### ISSUE THREAD

**Issue by liufeihong** [winlinvip/simple-rtmp-server#250]
强烈建议增加一个接收UDP TS流的实用功能！！！
最近在使用SRS，性能的确不错。但是我的使用环境是要接收前端众多硬件编码器推送过来的TS流，然后转换成多协议输出给多终端。
编码器输出的流标准为：协议，UDP单播或组播；视频编码，H.264；音频编码，AAC；
当前采用的解决方案是使用ffmpeg将其转换成rtmp推送给SRS，但是ffmpeg存在一个问题，不能以copy方式转发48KHz音频数据，音频要重新转码才行。
所以，如果SRS能够直接接收 UDP TS流就太方便了，能够帮助更多用户真正使用起来，希望斑竹考虑！

**Comment by jhkwei** [comment]
Udp需要处理丢包和错序，可以不处理，这些是内网的东西，丢包也是不可逆的，也不会重传，所以这些可以不考虑。

**Comment by liushengkai** [comment]
如果想解决UDP丢包和重传问题，不知道能不能使用UDT这个开源的方案实现，没有仔细的研究SRS的代码，我觉得可以试试，UDT的接口封装的也非常简单。

**Comment by winlinvip** [comment]
传输层不能用udt。
其实丢包就丢了，应该不管就好了。用超时来处理这种就可以了。

**Comment by winlinvip** [comment]
这个暂时推延到srs3解决了。

**Comment by winlinvip** [comment]
或者大家有空实现一个吧，我可以合并过来。
贫僧时间不够啊。

**Comment by jhkwei** [comment]
我初步实现了UDP demux，可是还一个大问题 audio adts to asc,
就是一般的视频48000HZ,还flv 最高才44100HZ，要把48000 down  to 44100

**Comment by liufeihong** [comment]
不一定非要将音频的采样率降到44.1KHz吧，我用过别人做的编码器，在FLV容器中封装的就是48KHz的音频，用起来很正常。

**Comment by jhkwei** [comment]
TS demux 初步测试完成了，谁有 h264 和 aac 的 TS 的流发一些给我，再测一下
https://github.com/jhkwei/ts_packet.git

**Comment by winlinvip** [comment]
Great work! NB~

**Comment by winlinvip** [comment]
准备在SRS2支持MPEG-TS over UDP。

**Comment by winlinvip** [comment]
在SRS上侦听一个UDP端口，接受TS流，解析后以RTMP发送到本地SRS。

**Comment by jhkwei** [comment]
我也是这么想的，这个做起来方便，简单

**Comment by jhkwei** [comment]
TS demux 基本测试完成了，看怎么弄到 SRS 中

**Comment by winlinvip** [comment]
提交pull request吧。

**Comment by winlinvip** [comment]
The rfc: doc/hls-mpeg-ts-iso13818-1.pdf

**Comment by jhkwei** [comment]
TS over UDP 组播占多，监听端口只适应单播，这里只好做成engine

**Comment by winlinvip** [comment]
RFC没有看清楚的地方是PCR这部分，包括系统时钟频率（SystemClockFrequency）：
```
2.4.2.1 System clock frequency
The value of the system clock frequency is measured in Hz and shall meet the following constraints:
27 000 000 − 810 ≤ system_clock_frequency ≤ 27 000 000 + 810
rate of change of system_clock_frequency with time ≤ 75 × 10−3 Hz/s
Bit rates defined in this Specification are measured in terms of system_clock_frequency. For example, a bit rate of
27 000 000 bits per second in the T-STD would indicate that one byte of data is transferred every eight (8) cycles of the
system clock.
```
没有搞清楚这个system clock frequency是干啥的。

以及PCR的计算：
```
2.4.2.2 Input to the Transport Stream system target decoder
Specifically:
PCR(i) = PCR_base(i) × 300 + PCR_ext(i) (2-1)
where:
PCR_base(i) = ((system_clock_ frequency × t(i)) DIV 300) % 233 (2-2)
PCR_ext(i) = ((system_clock_ frequency × t(i)) DIV 1) % 300 (2-3)
For all other bytes the input arrival time, t(i) shown in equation 2-4 below, is computed from PCR(i″) and the transport
rate at which data arrive, where the transport rate is determined as the number of bytes in the Transport Stream between
the bytes containing the last bit of two successive program_clock_reference_base fields of the same program divided by
the difference between the time values encoded in these same two PCR fields.
t(i) =
PCR(i″ )
system_clock_ frequency +
i − i″
transport_rate (i) (2-4)
where:
i is the index of any byte in the Transport Stream for i″ < i < i′.
i″ is the index of the byte containing the last bit of the most recent program_clock_reference_base field
applicable to the program being decoded.
PCR(i″) is the time encoded in the program clock reference base and extension fields in units of the system
clock.
The transport rate is given by
transport_rate(i) =
((i' – i″ ) × system_clock_frequency)
PCR(i') – PCR(i'') (2-5)
where
i′ is the index of the byte containing the last bit of the immediately following
program_clock_reference_base field applicable to the program being decoded.
NOTE – i″ < i ≤ i′
```

这个最初就没有搞清楚，看了一遍还是没有搞清楚：
1. 是否PCR是根据这个计算的？我看HLS生成的时候，PCR就直接用的dts加减一个常量。
2. 是否这个只是decoder的参考，参考啥？解码时根据pcr计算dts？
望高人指点下。

**Comment by jhkwei** [comment]
不是，两者同源，比如系统一个27kHZ的时钟，PCR你走你的，PTS ,DTS,走自己的，两者时钟同源，在解码时，解码器根据PCR校准自己的时钟，到时根椐DTS解码，DTS也不是必须的，要DTS主要自的是解码器缓存用来控制上溢下溢，flv的时间截差不多。如果要TS文件rtmp最好用PCR控制读的速度

**Comment by jhkwei** [comment]
上面也可以用DTS代替PCR，PCR就多余，如果还智能一些，两者都不要，自动计算帧率

**Comment by winlinvip** [comment]
![dtspts](https://cloud.githubusercontent.com/assets/2777660/5890257/c9307258-a48d-11e4-9841-8c5fd8429f0f.png)
为何pcr=dts-63000（即7ms），dts+=7ms, pts +=7ms？
nginx为何要调整pcr和dts/pts？
如果直接pcr=dts，然后dts和pts不调整，会怎样？

在`四野`的指点下，pcr的用途也搞清楚了，用来校正编码器的时钟。
pcr不一定和dts和pts一起发，有可能单独发，用来校正时钟。
只是nginx-rtmp在每个关键帧前面发的，但是实际上不一定。
那就是说，pcr设置为dts，dts和pts不调整，完全是没有问题的。

**Comment by winlinvip** [comment]
pcr的改动，参考hls的commit：https://github.com/winlinvip/simple-rtmp-server/commit/1835957a2b09b4dc7f393649f7e7b295c90e5b64

**Comment by winlinvip** [comment]
可使用ffmpeg输出MPEGTS over UDP：
```
ffmpeg -re -i doc/source.200kbps.768x320.flv -acodec copy -vcodec copy -bsf h264_mp4toannexb -f mpegts -y udp://127.0.0.1:1935
```

**Comment by jhkwei** [comment]
这个有问题的呢，这些视频流99.9%是组播流。

**Comment by winlinvip** [comment]
组播暂时不支持，先支持udp单播。

**Comment by winlinvip** [comment]
![pes-av](https://cloud.githubusercontent.com/assets/2777660/5986231/ab69e5d6-a92b-11e4-9a02-ec64a5546340.jpg)
audio一个包就包含了很多，而且时间戳比video小，这种得自己解包后重新打时间戳

**Comment by winlinvip** [comment]
现在PES流解析没有问题了,音频是ADTS结构：
```
[2015-01-31 12:17:15.164][trace][6568][103] mpegts: got Audio stream=AAC, dts=129060, pts=129060, size=2924, us=0, cc=15, sid=0xc0(A-0)
(gdb) x /64xb msg[0].payload[0].bytes()
0x87bef0:	0xff	0xf1	0x50	0x80	0x0b	0xdf	0xfc	0x21
0x87bef8:	0x11	0x45	0x00	0x14	0x50	0x01	0x46	0xf3
0x87bf00:	0xf1	0x0a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a
0x87bf08:	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a
0x87bf10:	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a
0x87bf18:	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a
0x87bf20:	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a
0x87bf28:	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a	0x5a
```

**Comment by winlinvip** [comment]
支持从PES中取出h264视频推到服务器。音频的稍微麻烦点，明天再弄。足足改了7天才改完，mpegts真麻烦。

**Comment by winlinvip** [comment]
配置：
```
stream_caster {
    enabled         on;
    caster          mpegts_over_udp;
    output          rtmp://127.0.0.1/live/livestream;
    listen          1935;
}
```
