### ISSUE TITLE
同一直播流，编码器重新推送后，HLS异常

### ISSUE THREAD

**Issue by hx227** [winlinvip/simple-rtmp-server#280]
系统：centos6.6 x64
编译器版本：gcc 4.4.7
编码器：ffmpeg
服务器：srs1.0.13
srs 配置文件：
```
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
srs_log_level       warn;
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
        hls_on_error    ignore;
    }
}
```

客户端：vlc 2.1.5
http server 使用srs自带的nginx

编码器推送rtmp直播流，rtmp://ipaddr/live/stream1，vlc 播放 http://ipaddr/live/stream1.m3u8 正常，当编码器断开连接，重新推送该流，vlc 播放http://ipaddr/live/stream1.m3u8 画面会停止在编码器断开时的画面。我发现此时在hls_path/live 目录下，并不会循环生成ts文件，而是一直在写最后一个文件 stream1-11355.ts.tmp，而m3u8文件此时也不会更新。

**Comment by winlinvip** [comment]
编码器：FFMPEG版本是什么？编码参数是什么？流地址是什么？

**Comment by winlinvip** [comment]
https://github.com/winlinvip/simple-rtmp-server/commit/87519aaae835199e5adb60c0ae2c1cd24939448c

可能是假的annexb格式导致。

**Comment by winlinvip** [comment]
SRS2已经重写了HLS，这个问题会在SRS2中修正。
