### ISSUE TITLE
SRS客户端在推流过程中，创建的srs rtmp连接会一直占用资源

### ISSUE THREAD

**Issue by zustchf** [winlinvip/simple-rtmp-server#287]
SRS客户端在推流过程中，创建的srs rtmp连接会一直占用资源，怀疑是在所建立的连接在推流的一直在吃内存，可能是在记录状态或者什么东西，对于嵌入式设备，这一点有点致命

**Comment by winlinvip** [comment]
srslibrtmp么？什么环境？

**Comment by zustchf** [comment]
嵌入式ARM Linux的环境下，srs服务端和客户端都在本地，使用的master的版本，使用了1月26号的版本后，情况有所改善，不会跑了很短的一段时间后就会将内存吃空，后来把输出打印信息输出到输出端口以及打印等级提到error之后，可以运行好几天，但是每隔一段时间，内存还是会有所减少，此外，用jwplayer播放，如果播放卡住了，虽然srs服务端一直在切片，但是一定得刷新页面才能正常播放

2015-03-02 

zustchf 



发件人：winlin <notifications@github.com>
发送时间：2015-03-01 17:37
主题：Re: [simple-rtmp-server] SRS客户端在推流过程中，创建的srs rtmp连接会一直占用资源 (#287)
收件人："winlinvip/simple-rtmp-server"<simple-rtmp-server@noreply.github.com>
抄送："zustchf"<zustchf@163.com>

srslibrtmp么？什么环境？
