### ISSUE TITLE
软件一致性问题

### ISSUE THREAD

**Issue by winlinvip** [winlinvip/simple-rtmp-server#288]
有些设计或架构，甚至代码的变更，是由于考虑软件一致性的。

**Comment by winlinvip** [comment]
关于这个commit：https://github.com/winlinvip/simple-rtmp-server/commit/27e0521ace00032bde080f43890af9c4f8f3138c#diff-354794cbcfee1046467f16b8a53d8ba2L1489

如果h264遇到info frame，解码时会有问题，目前的处理是：
```
    if ((ret = codec->video_avc_demux(video->payload, video->size, sample)) != ERROR_SUCCESS) {
        if (sample->frame_type == SrsCodecVideoAVCFrameVideoInfoFrame) {
            srs_warn("hls igone the info frame, ret=%d", ret);
            return ERROR_SUCCESS;
        }
        srs_error("hls codec demux video failed. ret=%d", ret);
        return ret;
    }
```

即解码失败时，如果是info frame，就重置错误码。
实际上这个会对于软件一致性有点问题，更好的处理是：
1. 在codec->video_avc_demux解码出来info frame后立刻返回。
2. 在SrsHls::on_video时发现是info frame也丢弃视频。
因为这个属于明确需要忽略的包，而不是在错误后忽略（更像是堵上漏洞）。

改成：

**Comment by winlinvip** [comment]
关于这个commit：https://github.com/winlinvip/simple-rtmp-server/commit/a402ca7120094f3b27eb7a4216aaa24cfac6d92c

**Comment by wuxianlijiang** [comment]
支持你！掌门人@

**Comment by winlinvip** [comment]
关于http dvr api，参考https://github.com/winlinvip/simple-rtmp-server/issues/179#issuecomment-75531742，实际上这个功能虽然实现了，但是违反了一致性。
SRS有reload功能，在修改了配置后reload不需要重启就可以生效配置。
如果用户调用http dvr api，现在的实现是会修改内存中的配置。若用户再修改配置文件，然后reload，则导致dvr重置。
保证一致性的做法是，先修改dvr机制，支持流级别的配置。然后提供http api修改配置文件和reload。
因此我在SRS2中会撤销http dvr api功能，延迟实现。

**Comment by winlinvip** [comment]
关于这个bug：#310，即aac的profile和object type，这个之前SRS一直是迷糊的，原因是最初看nginx代码中有时候加1，有时候减1，标准文档也没有搞清楚。最后终于把标准文档搞清楚了，具体参考bug。
这个有个一致性问题，是关于AAC LC/HE/HEv2，这个的处理会引入一致性问题。本质上是：
AAC LC，一般常用的profile。
AAC HE = AAC LC + SBR，即profile还是一样，但是object是5（reserved），由于服务器不识别内容，因此只是这个标记需要转换。
AAC HEv2 = AAC LC + SBR + PS，和HE一样，也是object是29（reserved）。
实际上这个问题很简单，只需要在object和profile转换时修改一点点就可以。而如果引入is_sbr和is_ps，这种状态变量维护的成本很高。

参考nginx修改：https://github.com/arut/nginx-rtmp-module/commit/3a5f9eea78fc8d11e8be922aea9ac349b9dcbfc2
参考SRS修改：https://github.com/winlinvip/simple-rtmp-server/commit/8dbabe3708a3628fa7cd5f0a9427137798a5a677

**Comment by winlinvip** [comment]
kbps带宽统计中出现一致性问题，由于接口定义包含了多个功能导致：
```
class IKbpsDelta
{
public:
    IKbpsDelta();
    virtual ~IKbpsDelta();
public:
    /**
    * resample to generate the value of delta bytes.
    */
    virtual void resample() = 0;
    /**
    * get the send or recv bytes delta.
    */
    virtual int64_t get_send_bytes_delta() = 0;
    virtual int64_t get_recv_bytes_delta() = 0;
};
```
实际上，两个get函数除了获取delta（字节差值）之外，还将delta清空。
原因在于，之前的设计是这么使用的：
```
* 2. server to calc kbps by add_delta():
*       SrsKbps* kbps = ...;
*       kbps->set_io(NULL, NULL)
*       for each connection in connections:
*           delta->resample()
*           kbps->add_delta(delta)
*       kbps->sample()
*       kbps->get_xxx_kbps().
```
也就是说，譬如一个RTMP connection，可以在resample后就可以得到这段期间的bytes的delta，在获取差值的函数（上面的接口）中做了获取和清除两个事情。导致这个维护性很低，很难理解到底这个resample是个什么概念。

实际上应该加上cleanup清除delta差值的函数：
```
/**
* the interface which provices delta of bytes.
* for a delta, for example, a live stream connection, we can got the delta by:
*       IKbpsDelta* delta = ...;
*       delta->resample();
*       kbps->add_delta(delta);
*       delta->cleanup();
*/
class IKbpsDelta
{
public:
    IKbpsDelta();
    virtual ~IKbpsDelta();
public:
    /**
    * resample to generate the value of delta bytes.
    */
    virtual void resample() = 0;
    /**
    * get the send or recv bytes delta.
    */
    virtual int64_t get_send_bytes_delta() = 0;
    virtual int64_t get_recv_bytes_delta() = 0;
    /**
    * cleanup the value of delta bytes.
    */
    virtual void cleanup() = 0;
};
```
使用方法：
```
* 2. server to calc kbps by add_delta():
*       SrsKbps* kbps = ...;
*       kbps->set_io(NULL, NULL)
*       for each connection in connections:
*           IKbpsDelta* delta = connection; // where connection implements IKbpsDelta
*           delta->resample()
*           kbps->add_delta(delta)
*           delta->cleanup()
*       kbps->sample()
*       kbps->get_xxx_kbps().
```

**Comment by winlinvip** [comment]
对于这个commit：https://github.com/winlinvip/simple-rtmp-server/commit/692b751da8d3ed4695529e93a5f768d3cfa0ec52
以及bug：#351, #321 
HLS输出路径时，只配置了路径，无法配置m3u8和ts路径。
实际上DVR时的时间变量可以用在这个地方，也就是提供两个变量`hls_m3u8_file`和`hls_ts_file`，里面包含变量，进行替换。
这样可以解决hls重启后片号重置为0的问题。

**Comment by winlinvip** [comment]
关于这个commit：https://github.com/winlinvip/simple-rtmp-server/commit/e56d7add444742c997ddb03f259d14cfc797f84e
虽然只是配置的解析，但是改过之后明显理解起来要更好。另外，对于偏好开或者偏好关，用宏定义来解析，譬如：
```
bool SrsConfig::get_http_api_enabled(SrsConfDirective* conf)
{
    if (!conf) {
        return false;
    }
    
    conf = conf->get("enabled");
    if (!conf || conf->arg0().empty()) {
        return false;
    }
    
    return SRS_CONF_PERFER_FALSE(conf->arg0());
}
```
这个会默认返回false，并且偏好返回false。譬如，配置为`enabled xxx;`也是flase。

**Comment by winlinvip** [comment]
migarate to https://github.com/simple-rtmp-server/srs/issues/1
