### ISSUE TITLE
启用SRS内部http服务后可出现崩溃

### ISSUE THREAD

**Issue by xlxlxll** [winlinvip/simple-rtmp-server#289]
启用内部http，此时访问http://srs-server-ip:port/live
SRS崩溃，并报错
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by winlinvip** [comment]
SRS1.0的http服务器是实验性的，bug不修。
SRS2.0已经重写了http服务器，请使用2.0的http服务器。

**Comment by winlinvip** [comment]
SRS1.0的http服务器因为是实验性的，实验性的所以不推荐用，而且1.0已经release，所以bug不修正了。
SRS2.0的http服务器是可以商用的，所以推荐直接用srs的http服务器，不必使用外部http服务器了。

**Comment by wuxianlijiang** [comment]
马上尝试2.0

**Comment by winlinvip** [comment]
额，2.0目前是开发版，虽然http不会崩溃，其他地方还是会崩溃，不建议在服务环境用SRS2，还是得用SRS1.

**Comment by wuxianlijiang** [comment]
明白了！
