### ISSUE TITLE
釆集 TS over UDP问题

### ISSUE THREAD

**Issue by jhkwei** [winlinvip/simple-rtmp-server#292]
釆集udp ts 问题，现在的方式只能适应SPTS，对于MPTS不适应，所以我想直接发送h264和aac裸流，现在有几个问题请教一下：

1）如果h264和aac是独立线程处理，它们之间要不要互斥;
2）就是pts和dts问题，这个pts和dts是不是和TS中的pts和dts有区别，我看代码中Timestamp 后面就是pts，单位是milliseconds，而TS流是的pts不是milliseconds，是不是要转换成milliseconds
3）MPTS 中有流要转码，如果我把MPTS ==> SPTS ==> ffmeg ==> SRS， 在SPTS ==> ffmeg这一步中是我现在能想到的就是通过UDP发送过去，ffmpeg 可以支持fifo这类传送方式吗，或者其它简单方式

**Comment by winlinvip** [comment]
SRS使用ffmpeg实现采集功能，也就是srs会启动一个ffmpeg进程。
你问的似乎是ffmpeg内部怎么实现的，这个我不清楚。
如果只是使用ffmpeg，那么你只需要用ffmpeg命令采集ts推给srs，如果可行，就可以配置srs让srs启动ffmpeg。
