### ISSUE TITLE
Delivery MPEG-DASH

### ISSUE THREAD

**Issue by winlinvip** [winlinvip/simple-rtmp-server#299]
MPEG-DASH点播和直播支持。

**Comment by winlinvip** [comment]
url: 
    http://ossrs.net:8081/dash/car.mpd

players:
    http://dashas.castlabs.com/demo/try.html
    http://digitalprimates.net/dash/DashTest.html

**Comment by winlinvip** [comment]
http://dash-mse-test.appspot.com/dash-player.html

http://dash-mse-test.appspot.com/dash-player.html?url=http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd
这个好像是js实现的dash啊。

**Comment by winlinvip** [comment]
https://w3c.github.io/media-source/
貌似chrome提的是这个标准。。。

**Comment by winlinvip** [comment]
http://code.google.com/p/chromium/issues/detail?id=54198
https://code.google.com/p/chromium/issues/detail?id=109652#c2

**Comment by xlphs** [comment]
MPEG-DASH VOD(点播) requires .mpd (manifest) for each media. Say we need to serve a mp4, The manifest can be generated by fragmenting it, or if the media is already fragmented then scan for mp4 boxes/atoms. Once manifest is generated, server only needs to serve the manifest and mp4 boxes (requires byte range support). On the client side, flash/js video player loads .mpd file, then download desired segments.

The power of MPEG-DASH is in adapting to bandwidth limit, the manifest may contain high and low quality representations of the same media, client can choose one of them based on current bandwidth.

Nginx already supports byte range header, so most of the complexity comes from creating the manifest, and processing user-supplied media file.

**Comment by winlinvip** [comment]
I won't introduce dash in SRS2, maybe in SRS3+.
