### ISSUE TITLE
Convert raw h264 to flv stream

### ISSUE THREAD

**Issue by allspace** [winlinvip/simple-rtmp-server#300]
I want to convert a raw h264 live stream to flv stream (means not a flv file, but deliver flv data via http protocol)

I am thinking about how to make use of srs_librtmp. I can manage to replace those srs_flv_* functions work on buffer, instead of file.

But still do not have full idea about how to make use of those srs_flv_* functions to convert h264 to flv. Any suggestion?

**Comment by allspace** [comment]
BTW: it seems srs flv encoder does not support multi-threading? as static variable is used in SrsFlvEncoder::write_tag.

**Comment by winlinvip** [comment]
1. To publish h.264 raw to rtmp: Please refer to srs_h264_raw_publish.c
2. To remux rtmp to flv stream, read #293 
3. About the static variable, file a bug and I will fix it.
