### ISSUE TITLE
thread-safe support for srs_librtmp，支持线程安全

### ISSUE THREAD

**Issue by allspace** [winlinvip/simple-rtmp-server#302]
static variables are currently used in srs_librtmp. Not all of them will cause problem for multithreading applications, but the following ones will cause problem:
SrsFlvEncoder::write_tag in srs_kernel_flv.cpp

There are also static variable usage in srs_kernel_utility.cpp, srs_librtmp.cpp, srs_protocol_rtmp.cpp, srs_protocol_handshake.cpp, srs_protocol_utility.cpp, but not sure if they are used when srs_librtmp is used as a client library, instead of a server.

**Comment by winlinvip** [comment]
没有必要使用局部静态变量，改成局部变量或者context中的变量。

**Comment by winlinvip** [comment]
fixed
