### ISSUE TITLE
SRS2.0 Export Srs Librtmp失败

### ISSUE THREAD

**Issue by backylee** [winlinvip/simple-rtmp-server#305]
./configure --export-librtmp-single=$dir时，提示：

[root@localhost trunk]# ./configure --export-librtmp-single=/home/winlin/srs-librtmp
regenerate config: --prefix=/usr/local/srs --without-hls --without-dvr --without-nginx --without-ssl --without-ffmpeg --without-transcode --without-ingest --without-stat --without-http-callback --without-http-server --without-stream-caster --without-http-api --with-librtmp --with-research --without-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace
srs-librtmp target dir exists: /home/winlin/srs-librtmp. 
[root@localhost trunk]# ./configure --export-librtmp-single=/home/winlin/srs-librtmp
regenerate config: --prefix=/usr/local/srs --without-hls --without-dvr --without-nginx --without-ssl --without-ffmpeg --without-transcode --without-ingest --without-stat --without-http-callback --without-http-server --without-stream-caster --without-http-api --with-librtmp --with-research --without-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace
cp: cannot stat `src/rtmp/*': No such file or directory
export src failed, ret=1
[root@localhost trunk]#

**Comment by winlinvip** [comment]
fixed
