### ISSUE TITLE
DVR配置部分能否实现APPEND方式续写同名文件？能否支持HttpAPI调用开始/停止DVR动作？

### ISSUE THREAD

**Issue by walkermi** [winlinvip/simple-rtmp-server#306]
如题，目前DVR有两种计划：session、segment。

假如这样设置
dvr_path     /record/[stream].flv;
能否当推流中断后恢复推送，继续在该文件追加写入。这样的场景还是不少的。

另外能不能支持API调用启停DVR？Start DVR调用后，开始推流即开始写入，中断后等待恢复后继续追加，直到Stop DVR。

**Comment by winlinvip** [comment]
参考：#179，append模式已经支持。但是http dvr api因为改动复杂，推延到下一个版本。
