### ISSUE TITLE
ubuntu12下交叉编译srs报错

### ISSUE THREAD

**Issue by backylee** [winlinvip/simple-rtmp-server#308]
ubuntu12下，
用apt-get安装arm编译器：
sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
./configure --with-arm-ubuntu12 && make
成功编译；

换成海思的交叉编译工具arm-hisiv100-linux-uclibcgnueabi-gcc，执行：
export SrsArmCC="arm-hisiv100-linux-uclibcgnueabi-gcc" &&
export SrsArmGCC="arm-hisiv100-linux-uclibcgnueabi-gcc" &&
export SrsArmCXX="arm-hisiv100-linux-uclibcgnueabi-g++" &&
export SrsArmAR="arm-hisiv100-linux-uclibcgnueabi-ar" &&
export SrsArmLD="arm-hisiv100-linux-uclibcgnueabi-ld" &&
export SrsArmRANDLIB="arm-hisiv100-linux-uclibcgnueabi-ranlib" &&
./configure --with-arm-ubuntu12 --with-ssl --with-hls --with-librtmp
出现如下错误
Making examples
make[2]: Entering directory `/home/bk/cross_srs-csdn/trunk/objs/st-1.9/examples'
arm-hisiv100-linux-uclibcgnueabi-gcc -DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -I../LINUX_3.5.0-17-generic_DBG -c res.c -o ../LINUX_3.5.0-17-generic_DBG/res.o
res.c: In function 'parse_answer':
res.c:108: warning: implicit declaration of function 'dn_skipname'
res.c: In function 'query_domain':
res.c:142: warning: implicit declaration of function 'res_mkquery'
arm-hisiv100-linux-uclibcgnueabi-gcc -DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -I../LINUX_3.5.0-17-generic_DBG lookupdns.c ../LINUX_3.5.0-17-generic_DBG/res.o ../LINUX_3.5.0-17-generic_DBG/libst.a -lresolv  -o ../LINUX_3.5.0-17-generic_DBG/lookupdns
../LINUX_3.5.0-17-generic_DBG/res.o: In function `parse_answer':
/home/bk/cross_srs-csdn/trunk/objs/st-1.9/examples/res.c:108: undefined reference to `dn_skipname'
/home/bk/cross_srs-csdn/trunk/objs/st-1.9/examples/res.c:115: undefined reference to `__ns_get16'
/home/bk/cross_srs-csdn/trunk/objs/st-1.9/examples/res.c:117: undefined reference to `__ns_get16'
../LINUX_3.5.0-17-generic_DBG/res.o: In function `query_domain':
/home/bk/cross_srs-csdn/trunk/objs/st-1.9/examples/res.c:142: undefined reference to `res_mkquery'
collect2: ld returned 1 exit status
make[2]: *** [../LINUX_3.5.0-17-generic_DBG/lookupdns] Error 1
make[2]: Leaving directory `/home/bk/cross_srs-csdn/trunk/objs/st-1.9/examples'
make[1]: *** [examples] Error 2
make[1]: Leaving directory `/home/bk/cross_srs-csdn/trunk/objs/st-1.9'
make: *** [linux-debug] Error 2
build st-1.9 failed, ret=2
root@ubuntu:/home/bk/cross_srs-csdn/trunk#

**Comment by winlinvip** [comment]
我会在SRS2中编译时禁用st的examples。

**Comment by jhkwei** [comment]
2.0 可不可以用1.0的st，这个没有编译过去，去掉了examples也过不了。

**Comment by winlinvip** [comment]
应该就是examples的问题，我会加个patch来禁用。
