### ISSUE TITLE
Memory fragments for long run

### ISSUE THREAD

**Issue by allspace** [winlinvip/simple-rtmp-server#313]
For every rtmp message, srs allocates memory after received the message from publisher (i.e. read_message_payload), and frees memory after published the message to all subscribers. (It does try to avoid memory copy by sharing one message among all subscribers)

Will this model cause too many memory fragments after run for long time? as it allocates/frees memory for every rtmp message.

Please correct me if I am wrong.

**Comment by winlinvip** [comment]
Please test and finger it out.
