### ISSUE TITLE
建议增加类似“Disabling idle streams in nginx-rtmp-module”

### ISSUE THREAD

**Issue by walkermi** [winlinvip/simple-rtmp-server#315]
The new directive is idle_streams. Default value on is consistent with the current behavior. If turned off subscribers will not be able to connect to idle (not published to) streams and will be disconnected when stream publisher disconnects.

application live {
    live on;
    idle_streams off;
}

仅供参考，呵呵。

【掌门】可爱的雷万宝(xxxxxxxx) 2015/2/28 21:06:13
and will be disconnected when stream publisher disconnects.
----- 这个是 “ 如果流断了，那么订阅者也断线”
【掌门】可爱的雷万宝(xxxxxxxx) 2015/2/28 21:06:46
and will be disconnected when stream publisher disconnects.
 这个功能 ，实际上 很影响 编程  和 用户体验 
有时候 ，RTMP 只是临时断流 。可能 几秒钟以后 就 回复 了
【掌门】可爱的雷万宝(xxxxxxxx) 2015/2/28 21:07:23
但是， 你这么 一搞。。把所有用户 都 T掉了 
【掌门】可爱的雷万宝(xxxxxxxx) 2015/2/28 21:07:51
RTMP 只是临时断流 。可能 几秒钟以后 就 回复 了--- 这个时候 播放器 会 hold 住的 。。等流 恢复了 。。自动播放 
rtmp auto republish 。。是这个说法吧
【盟主】北京-豹(xxxxxxxx) 2015/2/28 21:08:49
我想想啊
【掌门】可爱的雷万宝(xxxxxxxx) 2015/2/28 21:09:20
你不用想。。这个 还影响到  回源的 高可用性设计 
比如 。我准备 了 3路 流  用于  灾备。。。
【盟主】北京-豹(xxxxxxxx) 2015/2/28 21:10:06
也是，光考虑单台服务的情况了
【掌门】可爱的雷万宝(xxxxxxxx) 2015/2/28 21:10:17
嗯 
所以 。。我说了 。。winlin 小伙子  还是 不错的 。。一看就是有实战经验的 

雷兄，说的也很有道理，供参考。

**Comment by winlinvip** [comment]
以后看是否加进去。
