### ISSUE TITLE
SRS的统计功能, the statistic api.

### ISSUE THREAD

**Issue by walkermi** [winlinvip/simple-rtmp-server#316]
可以参考一下nginx的，不过他这个其实统计的内容也很少
![qq 20150228214658](https://cloud.githubusercontent.com/assets/1332874/6426405/699134d8-bf93-11e4-8404-cde1661c1446.jpg)
![123456](https://cloud.githubusercontent.com/assets/1332874/6426406/8bcbdfc6-bf93-11e4-9074-159a451ab24b.jpg)

可以考虑以API方式提供，调用放获取到基本信息，自行决定以什么方式进行统计。如果能像nginx样提供给简单页面当然更好。

编码信息、客户端数量、在线状态、在线时间、进出流量、进出带宽峰值统计……这些都是必要的吧，其他还有什么？

**Comment by winlinvip** [comment]
我会在SRS2支持。

**Comment by winlinvip** [comment]
#173 和这个相关。

**Comment by winlinvip** [comment]
提供：
1. 各个流的带宽，vhost的带宽，服务器带宽。
2. 流的码率：30秒，300秒，平均码率。
3. 流的编解码信息。
4. 流的状态和运行时间。

**Comment by winlinvip** [comment]
服务器的带宽已经提供了：http://dev:1985/api/v1/summaries
包含所有的RTMP带宽，包含publish和play带宽。

**Comment by winlinvip** [comment]
流的编码信息已经提供：http://dev:1985/api/v1/streams
```
"video": {
    "codec": "H264",
    "profile": "High",
    "level": 3.2
}, 
"audio": {
    "codec": "AAC",
    "sample_rate": 44100,
    "channel": 2,
    "profile": "LC"
}
```

**Comment by winlinvip** [comment]
流的字节数数据已经提供，3秒更新一次：http://dev:1985/api/v1/streams
```
"send_bytes": 4215,
"recv_bytes": 787465,
```
每隔一段时间更新一次，单位是字节bytes(B)
更新频率是：SRS_SYS_NETWORK_RTMP_SERVER_RESOLUTION_TIMES × SRS_SYS_CYCLE_INTERVAL，目前是3秒。

**Comment by winlinvip** [comment]
以后还可以提供更多，先这样了
