### ISSUE TITLE
haw to Specifies external command with arguments to be executed on play event

### ISSUE THREAD

**Issue by astralink** [winlinvip/simple-rtmp-server#318]
i try srs it work very fast . i want to use it rather than nginx rtmp .
i want to run transcode like nginx 
for live transcode at nginx i use Exec wrapper in bash 
example 
http://example.com/tv1.ts -c copy -f flv rtmp://localhost/$app/$name name=mystream;
rtmp://example.com/live/livestream swfUrl=http://example.com/swf pageUrl=http://example.com/Live/ -c copy -f flv rtmp://localhost/$app/$name name=mystream;

**Comment by winlinvip** [comment]
https://github.com/winlinvip/simple-rtmp-server/wiki/v1_EN_FFMPEG
https://github.com/winlinvip/simple-rtmp-server/wiki/v1_CN_FFMPEG

**Comment by astralink** [comment]
sorry may be i am explain in mistake words ..  i see that transcode work when do publish stream with external cmd with srs like "ffmpeg -i http://remotehost/play.m3u8 -c copy -f flv rtmp://localhost/live/stream_name"
haw i can do this like nginx
"Creates pull relay. Stream is pulled from remote machine and becomes available locally. It only happens when at least one player is playing the stream locally."
so haw i will pull stream from remote host to local host when client play and stop pull when last client stop play ?

**Comment by astralink** [comment]
with simple rtmp i can do 
vhost __defaultVhost__ {
    mode            remote;
    origin          rtmp.hostname:1935;
}

what i can do 
for 
orgin http://hostname/play.m3u8
or
orgin rtmp://example.com/live/livestream swfUrl=http://example.com/swf pageUrl=http://example.com/Live/

**Comment by winlinvip** [comment]
I see, you need when user play HLS, the edge pull from origin.
You can use reverse proxy or web cache for hls edge. SRS does not provide the HTTP edge right now.

**Comment by astralink** [comment]
thanks .. 
what about 
pull rtmp://cdn2.example.com/another/a?b=1&c=d pageUrl=http://www.example.com/video.html swfUrl=http://www.example.com/player.swf live=1 name=channel_a;
this from nginx 
haw to auto pull stream from remote complex rtmp url to local srs server like nginx . 
*.note i can transcode any stream by ffmpeg and push it to srs but this will take more bandwidth if they still work all time  i need to save bandwidth 

by nginx i can use tow way 

first one that 
Creates pull relay. Stream is pulled from remote machine and becomes available locally. It only happens when at least one player is playing the stream locally.
so add to config
pull rtmp://cdn2.example.com/another/a?b=1&c=d pageUrl=http://www.example.com/video.html swfUrl=http://www.example.com/player.swf live=1 name=channel_a;
 
second one 
Exec wrapper in bash

so add to config

application myapp {
    live on;

    exec /var/scripts/exec_wrapper.sh $name;
    exec_kill_signal term;
}

#################################################################
#!/bin/bash

on_die ()
{
    # kill all children
    pkill -KILL -P $$
}

trap 'on_die' TERM
ffmpeg -i rtmp://localhost/myapp/$1 -c copy -f flv rtmp://localhost/myapp2/$1 &
wait
################################################################
haw i can do any one from previous solution by srs ? ..

**Comment by winlinvip** [comment]
Try forward or ingest:
https://github.com/winlinvip/simple-rtmp-server/wiki/v1_EN_Forward
https://github.com/winlinvip/simple-rtmp-server/wiki/v1_CN_Forward

https://github.com/winlinvip/simple-rtmp-server/wiki/v1_EN_Ingest
https://github.com/winlinvip/simple-rtmp-server/wiki/v1_CN_Ingest
