### ISSUE TITLE
保留SRS运行的关键信息，重启时继续处理

### ISSUE THREAD

**Issue by wenjiegit** [winlinvip/simple-rtmp-server#321]
【躺尸】凯(147492361) 9:49:01 
请教大家一个问题， 就是 rtmp 切 hls 的片的时候， 我重起了以后， 片又从最开始切起， 有法子， 让他从重起之前切吗？ 从开始切的话，放 CDN 中会显示重复的画面。

保留上一次的切片号，可以让CDN回源非常方便，而不用做主动刷新动作。

**Comment by winlinvip** [comment]
1. 改变这个概念，不仅仅是保存hls切片号，而是保存运行信息。这样有益于完整性，否则要保存其它的信息时又得加。
2. 这个是optional的，要考虑段错误时，用户删除这个信息时的处理。通过配置选择是否开启，默认开启。

**Comment by winlinvip** [comment]
第一个系统信息：
1. HLS 保留上一次切片号，方便CDN回源
2. HLS 保留target duration，规范中说这个是不变的，SRS会让它变大，因此和配置可能不一样，需要保存。
3. 保留HLS的m3u信息，上次的切片信息，重启时可以恢复。

**Comment by winlinvip** [comment]
#209 可以在系统重启时清理这些ts片，不过不好实现，若需要接着切片，那么就要保留。所以只能是等待一定时间，如果还没有流上来就清理掉，但这个就麻烦了。

**Comment by winlinvip** [comment]
如果能配置hls的m3u8和ts路径，那么就可以避免片号重复的问题：
```
        hls_ts_file     [app]/[stream]-[timestamp]-[seq].ts;
```
参考：#351，以及commit：https://github.com/winlinvip/simple-rtmp-server/commit/692b751da8d3ed4695529e93a5f768d3cfa0ec52
