### ISSUE TITLE
HTTP FLV Live Stream只能发布一路流

### ISSUE THREAD

**Issue by zhao-xiang** [winlinvip/simple-rtmp-server#322]
srs版本：2.0.130
同时推两路流到SRS（同一个vhost）：
rtmp://xxx/live/livestream1
rtmp://xxx/live/livestream2
http flv方式发布的只有livestream1.flv可以播放，想要livestream2.flv能播放，必须停止livestream1的推流，重启SRS，再推livestream2，也就是只能同时发布有一路flv。
rtmp方式发布的livestream1和livestream2都可以播放。

**Comment by winlinvip** [comment]
这个应该是bug，我找时间看看。

**Comment by winlinvip** [comment]
![http-flv-multiple-streams](https://cloud.githubusercontent.com/assets/2777660/6520740/f3755a82-c405-11e4-8e8d-7b4321162d33.png)
fixed

**Comment by winlinvip** [comment]
![http-flv](https://cloud.githubusercontent.com/assets/2777660/6520747/32f90d98-c406-11e4-9cb3-68e31cb82d9d.png)

延迟对比，vlc的大，flash小
