### ISSUE TITLE
HTTP FLV Live Stream触发edge回源

### ISSUE THREAD

**Issue by zhao-xiang** [winlinvip/simple-rtmp-server#324]
srs版本：2.0.133
测试环境：
编码器推流 ---(RTMP)--> SRS origin ---(RTMP)--> SRS edge ---(RTMP&FLV)--> 播放器；
直接播放FLV流，播放器提示StreamNotFound，需要先播放一次rtmp流后，FLV发布的才能播放。

**Comment by winlinvip** [comment]
需要http触发回源，SRS2会fix这个问题。

**Comment by winlinvip** [comment]
这个功能改成：hstrs(http stream trigger rtmp stream source)，由http流触发的rtmp流及RTMP边缘回源机制。

**Comment by winlinvip** [comment]
客户端访问http stream时，会加上vhost后找到http remux，譬如：
```
curl http://127.0.0.1:8080/live/livestream.flv
```
这个的host是ip地址，在配置中查找匹配host是__defaultVhost__，因此会在默认host下面找http remix配置，如果hstrs开启就创建ramp source，如果是边缘则开始回源。

同时，会创建一个mount挂载点，因为推流时on_publish才会创建挂载点，在这之前会导致404.

**Comment by zhao-xiang** [comment]
srs版本：2.0.138
启用hstrs后，srs无法启动报错：
[2015-03-14 14:11:09.666][error][3480][0][0] unsupported vhost http_remux directive hstrs, ret=1023

**Comment by winlinvip** [comment]
哈哈，还没有做完呢。

**Comment by zhao-xiang** [comment]
哈哈，坐等：)

**Comment by winlinvip** [comment]
支持了源站的hstrs，http-flv也可以像rtmp一样，在没有流的时候standby，等编码器推流上来了开始播放。
![hstrs origin](https://cloud.githubusercontent.com/assets/2777660/6651522/7a362ec6-ca81-11e4-9686-5e49a2c87baa.jpg)

**Comment by winlinvip** [comment]
2.0.139，支持源站hstrs。

**Comment by winlinvip** [comment]
edge也可以了，hstrs触发边缘rss回源，这样http-flv集群就可以了。
例如，使用源站配置：
```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        #ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        ffmpeg      ./objs/research/librtmp/srs_ingest_flv;
        engine {
            enabled          off;
            output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
}
```

边缘的配置：
```
listen              19351;
max_connections     1000;
daemon              off;
srs_log_tank        console;
pid                 ./objs/edge.pid;
http_server {
    enabled         on;
    listen          8080;
}
vhost __defaultVhost__ {
    mode remote;
    origin 127.0.0.1;
    http_remux {
        enabled     on;
        fast_cache  30;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
}
```

用vlc直接访问边缘：http://127.0.0.1:8080/live/livestream.flv
可以看到边缘回源了。
