### ISSUE TITLE
中文Ubuntu系统获取本机IP地址的错误

### ISSUE THREAD

**Issue by lvan100** [winlinvip/simple-rtmp-server#325]
在配置文件 run.sh 中，正常情况下
ip=`ifconfig|grep "inet "|grep -v "127.0.0.1"|awk -F 'inet ' 'NR==1 {print $2}'|awk '{print $1}'|sed "s/addr://g"`
能够获得类似 “192.168.1.6” 这样的ip地址，但是在中文系统下获得的是 “地址:192.168.1.6” 
这样的字符串，解决这个问题很简单， 将配置文件改成
ip=`ifconfig|grep "inet "|grep -v "127.0.0.1"|awk -F 'inet ' 'NR==1 {print $2}'|awk '{print $1}'|sed "s/地址://g"`
就可以了。

**Comment by winlinvip** [comment]
不支持中文系统，有各种问题。

**Comment by lvan100** [comment]
还好，我在中文系统下面部署的。
