### ISSUE TITLE
2.0release make报错

### ISSUE THREAD

**Issue by zhao-xiang** [winlinvip/simple-rtmp-server#332]
src/app/srs_app_http.cpp: In member function ‘virtual void SrsHttpServeMux::hijack(ISrsHttpMatchHijacker*)’:
src/app/srs_app_http.cpp:534: error: no matching function for call to ‘find(__gnu_cxx::__normal_iterator<ISrsHttpMatchHijacker**, std::vector<ISrsHttpMatchHijacker*, std::allocator<ISrsHttpMatchHijacker*> > >, __gnu_cxx::__normal_iterator<ISrsHttpMatchHijacker**, std::vector<ISrsHttpMatchHijacker*, std::allocator<ISrsHttpMatchHijacker*> > >, ISrsHttpMatchHijacker*&)’
src/app/srs_app_http.cpp: In member function ‘virtual void SrsHttpServeMux::unhijack(ISrsHttpMatchHijacker*)’:
src/app/srs_app_http.cpp:543: error: no matching function for call to ‘find(__gnu_cxx::__normal_iterator<ISrsHttpMatchHijacker**, std::vector<ISrsHttpMatchHijacker*, std::allocator<ISrsHttpMatchHijacker*> > >, __gnu_cxx::__normal_iterator<ISrsHttpMatchHijacker**, std::vector<ISrsHttpMatchHijacker*, std::allocator<ISrsHttpMatchHijacker*> > >, ISrsHttpMatchHijacker*&)’
src/app/srs_app_http.cpp: In member function ‘virtual SrsRequest* SrsHttpMessage::to_request(std::string)’:
src/app/srs_app_http.cpp:1297: warning: comparison between signed and unsigned integer expressions
src/app/srs_app_http.cpp:1301: warning: comparison between signed and unsigned integer expressions
make[2]: *** [objs/src/app/srs_app_http.o] Error 1
make[2]: Leaving directory `/root/simple-rtmp-server/trunk'
make[1]: *** [server] Error 2
make[1]: Leaving directory `/root/simple-rtmp-server/trunk'
make: *** [default] Error 2

**Comment by winlinvip** [comment]
fixed
