### ISSUE TITLE
Cross compile , librtmp Makefile`s  GCC error

### ISSUE THREAD

**Issue by jhkwei** [winlinvip/simple-rtmp-server#333]
为了 Cross Compile 修改 configure 如下：
if [ $SRS_ARM_UBUNTU12 = YES ]; then
    #__SrsArmCC="arm-linux-gnueabi-gcc";
    #__SrsArmGCC="arm-linux-gnueabi-gcc";
    #__SrsArmCXX="arm-linux-gnueabi-g++";
    #__SrsArmAR="arm-linux-gnueabi-ar";
    #__SrsArmLD="arm-linux-gnueabi-ld";
    #__SrsArmRANDLIB="arm-linux-gnueabi-ranlib";

    __SrsArmCC="arm-hisiv200-linux-gcc";
    __SrsArmGCC="arm-hisiv200-linux-gcc";
    __SrsArmCXX="arm-hisiv200-linux-g++";
    __SrsArmAR="arm-hisiv200-linux-ar";
    __SrsArmLD="arm-hisiv200-linux-ld";
    __SrsArmRANDLIB="arm-hisiv200-linux-ranlib";
fi

可是发现 research/librtmp/Makefile
对应的GCC 还是按 GCC == arm-linux-gnueabi-gcc 来区分的，以致不能编译过去

**Comment by winlinvip** [comment]
你用的是1.0还是2.0？

**Comment by jhkwei** [comment]
1.0， 2.0 都有这问题
