### ISSUE TITLE
Makefile 传入的参数没有展开

### ISSUE THREAD

**Issue by jhkwei** [winlinvip/simple-rtmp-server#338]
本来应试是 make  EXTRA_CFLAGS=-DMD_HAVE_EPOLL
可是到了gcc 参数中 EXTRA_CFLAGS 没有被 -DMD_HAVE_EPOLL 替换掉
会出现
arm-hisiv200-linux-gcc -g EXTRA_CFLAGS=-DMD_HAVE_EPOLL -o xxx.o -c xxx.c

就会出现下面的编译错误：
arm-hisiv200-linux-gcc: EXTRA_CFLAGS=-DMD_HAVE_EPOLL: No such file or directory

**Comment by winlinvip** [comment]
怎么会这样子？
