### ISSUE TITLE
src/app/srs_app_http.cpp 少 #include <algorithm> 头文件

### ISSUE THREAD

**Issue by jhkwei** [winlinvip/simple-rtmp-server#339]
void SrsHttpServeMux::hijack(ISrsHttpMatchHijacker* h)
{
    std::vector<ISrsHttpMatchHijacker*>::iterator it = ::find(hijackers.begin(), hijackers.end(), h);
    if (it != hijackers.end()) {
        return;
    }
    hijackers.push_back(h);
}

src/app/srs_app_http.cpp:534: error: no matching function for call to 'find(_

**Comment by winlinvip** [comment]
已经fixed。
