### ISSUE TITLE
能否支持类似nginx-rtmp的“hls_base_url”的功能？

### ISSUE THREAD

**Issue by walkermi** [winlinvip/simple-rtmp-server#340]
https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls_base_url

【宗师】可爱的雷万宝  15:33:17
对了 对了 。。谁帮我 提一个 请求 ：

要求在 HLS 切片 里面 。。增加一个 配置 ，就是  ts切片的  域名前缀，例如：

http://www.woaiapian.com/  123.ts
【盟主】豹 15:34:00
这个@winlin 说可以在http服务器上配置，但是我没明白怎么配置
【宗师】可爱的雷万宝  15:34:19
虚拟？？
【盟主】孙悟空 15:34:20
宝哥
【宗师】可爱的雷万宝  15:34:24
改写？
【盟主】孙悟空 15:34:24
ffmpeg支持这个功能
我提的
【盟主】豹  15:34:39
大师兄说说？
【盟主】孙悟空  15:34:42
prefix_entry
segment支持这个
【宗师】可爱的雷万宝  15:35:02
嗯嗯。
大师兄 不愧是 大师兄 。。
【盟主】孙悟空  15:35:24
我找找
==
【宗师】可爱的雷万宝  15:36:08
但是，是这样啊 。。我现在 用 SRS  。。都是 不编译  nginx  和 ffmpeg 的 
【盟主】孙悟空  15:36:24
![qq 20150316154541](https://cloud.githubusercontent.com/assets/1332874/6662213/9803c4e0-cbf3-11e4-95cc-b64300bcc25b.png)

那你得改srs呢
srs里面需要getconfig一下，然后加一个prefixentry呢

**Comment by T-bagwell** [comment]
可以支持

**Comment by winlinvip** [comment]
已支持了。
