### ISSUE TITLE
ARM 祼流推送给自己错误

### ISSUE THREAD

**Issue by jhkwei** [winlinvip/simple-rtmp-server#344]
1） SRS ARM 服务器没有问题，因为在外部推流给 SRS ARM ，可得到服务器可分发
2） SRS ARM 祼流推送没有问题，因为推流给外部服务器， 可得到服务器可分发
3） ARM 祼流推送给自己上面的SRS服务器错误：握手失败

**Comment by jhkwei** [comment]
PC 祼流推送给自己测试是好的

**Comment by jhkwei** [comment]
错误是我自己没有设置环回地址

**Comment by winlinvip** [comment]
fixed
