### ISSUE TITLE
AAC mpeg4 以1.0时还可以裸推，2.0却不可以为什么一定要mpeg2

### ISSUE THREAD

**Issue by jhkwei** [winlinvip/simple-rtmp-server#347]
错误如下：adts: id must be 1(aac), actual 0(mp4a). ret=3055

**Comment by winlinvip** [comment]
2.0需要解析音频内容，mpeg2内容简单，mpeg4a里面的内容解析没有时间看。

**Comment by winlinvip** [comment]
fixed

**Comment by winlinvip** [comment]
有些实际上还是aac(1)，但是写成了mp4a(0)，实际上可以全部看成是aac。
