### ISSUE TITLE
HLS fault backup，HLS热备

### ISSUE THREAD

**Issue by winlinvip** [winlinvip/simple-rtmp-server#351]
凯  11:05:20
所以我和文杰象对于 HLS 之类，建议按时间来切片的原因也是这样，这样二台 srs 可以切出的片名都是一样，CDN 任意切，源站 keepalived 任意切， 比重起恢复到原来的块的 ID 的价值还大，就是基于这个原因
凯  11:05:52
嗯，只聊下。。。我也只是聊下这么多年，我对这些东西的看法。。。
北京-音视频  11:06:00
同意。
可爱的雷万宝  11:06:02
你们谈你们的。嘿嘿 我测我的。测出了问题反馈回来。 就行。
北京-音视频  11:06:08
这个是实用方面的。
北京-音视频  11:06:19
必须上线运营才知道的。
凯  11:06:23
想当年，蓝汛有个 FC 开发工程师一开始就讲，我要让一台 FC 服务 10G....
北京-音视频  11:06:38
角度不一样的。
可爱的雷万宝  11:06:42
@凯 你说的。nginx rtmp 模块有例子
北京-音视频  11:06:55
技术总监或者架构师要考虑全面的问题。
北京-音视频  11:07:16
核心开发人员要解决核心性能问题 。
凯  11:07:19
嗯。程序员们的出发角度不同引起的。
凯  11:07:39
可爱的雷万宝。。。见到这个名字总是感觉很萌。。
北京-音视频  11:07:44
调度系统讲起来东西也很多。
凯  11:07:59
你讲的 nginx rtmp 有什么样的例子啊？
北京-音视频  11:08:05
我也是一点建议。可能也不对。
可爱的雷万宝  11:08:06
nginx一般使用系统时间。 然后有说明如何保证多instance切片一致
孙悟空  11:08:23
凯哥现在咋解决的呢？
可爱的雷万宝  11:08:27
nginx rtmp hls的wiki
孙悟空  11:08:30
多hls互备
凯  11:08:45
我去看看
可爱的雷万宝  11:08:49
嗯
闿意  11:09:12
标记交换！
SDN可以用在你说的这种情况
winlin  11:09:17
在大牛云集的群中讲性能如何优化，是有压力的。
可爱的雷万宝  11:09:26
其实。有时候多参考人家做法也不错
winlin  11:09:31
什么是标记交换？
可爱的雷万宝  11:09:38
mpls
闿意  11:09:44
YES
winlin  11:09:48
那个是hls热备吧，要切出来的hls一样不太可能吧？
winlin  11:10:04
如果流断过，两个机器没有办法一样的切片了吧。如何处理这个。
闿意  11:10:06
SDN是,MPLS的变种，是一种更灵活的方式
凯  11:10:41
按时间取整的话，接下来的流都会输出成一样的名字了。
孙悟空  11:10:53
按时间戳？
凯  11:11:20
建议以时间戳按切片间隔来取整
孙悟空  11:11:42
时间戳如果联系两次回滚了的话……
可爱的雷万宝  11:11:44
@闿意 你那个是网络层的。
winlin  11:12:01
切片名字可以一样的。
孙悟空  11:12:03
在5s之内回滚了两次，或者赶上客户切源的时候
winlin  11:12:08
但是切片的内容如何一样？
闿意  11:12:14
都一样，数据层是建立在网络层之上的
winlin  11:12:22
这个才是最难的。
winlin  11:12:37
hls热备需要两个机器出的片一模一样，不然会有问题的。
孙悟空  11:12:36
是的
孙悟空  11:12:42
内容很关键
可爱的雷万宝  11:12:45
@闿意 但是很少有程序员熟悉
ZACH  11:13:27
 这个播放速度不错吧
闿意  11:13:45
会熟悉的，看看SDN就知道了
winlin  11:14:02
是在说HLS热备吗？
winlin  11:14:11
我也想做HLS热备，感觉没法做。
孙悟空  11:14:34

winlin  11:15:00
我想的是，除非两个HLS源站有通信，譬如约定好同一个关键帧到来后，开始切片。
凯  11:15:03
如果按时间片取整，热备在切换的时候，会有一定的时间数据不一致
winlin  11:15:05
否则是没有办法做的。
深圳-灰狐青鱼  11:15:08
只能拷贝文件
凯  11:15:27
这个不一致， 我个人认为相比起硬件挂和服务死，是可以接受的。
闿意  11:15:30
HLS 做成Edge模式，加载在SDN设备上
可爱的雷万宝  11:15:34
@winlin 我现在觉得吧。好多程序员都是闷着头。死命的干。两耳不闻其他事。 做出来。又发现其实人家已经实现过了
winlin  11:15:37
凯，你知道两个服务器，取上游的rtmp时，取到的数据是不一样的吧？
可爱的雷万宝  11:15:47
错了。发错了
凯  11:15:47
keepalived 切主从也会有一到二秒服务失效
winlin  11:16:01
雷妈，你是说HLS热备么？
可爱的雷万宝  11:16:04
@闿意。我现在觉得吧。好多程序员都是闷着头。死命的干。两耳不闻其他事。 做出来。又发现其实人家已经实现过了
可爱的雷万宝  11:16:12
@winlin 不是。
winlin  11:16:27
哦，我说HLS热备不太可能有人做得很牛了。
凯  11:16:28
取上游不一样，是因为缓存吗
winlin  11:16:38
不是啊，流媒体哦，
winlin  11:16:59
譬如中间时候，某个HLS源站重启了，
闿意  11:16:57
是的，你们在研究怎么做备份之类的，我认为这个东西就是个打包器的工作，为什么一定是服务器去干的事情呐？
凯  11:17:00
嗯，有几秒的失败是能接受的。数据库大多用 keepalived 来切主从，都会断几秒
凯  11:17:10
你还只是视频流，这个完全可以接受
winlin  11:17:21
不是的啊，
孙悟空  11:17:22
winlin的意思不是那个
winlin  11:17:32
重启后，再去取流，和另外一台就不一样了。
孙悟空  11:17:36
winlin的意思是rtmp新连接的timetampe都是从0开始
winlin  11:17:49
内容也不一样的
可爱的雷万宝  11:17:48
@winlin hls热备听你们说的确有难度
孙悟空  11:17:58
电视台现在也做不了全国电视同一个画面
winlin  11:18:05
所以除非这两台HLS源站之间有交流，否则做不了。
闿意  11:18:18
SDN可以交流啊
凯  11:18:27
现在都是使用 rtmp  本身的 timetampe 来切吗？
winlin  11:18:35
我觉得这个是可以在3.0做，SRS不就是擅长做这种么？
winlin  11:18:45
超级复杂的东西，而且挺有用。
winlin  11:18:49
杰哥，你做么？
winlin  11:18:55
我老了，干不动了。
凯  11:19:12

孙悟空  11:19:13
别啊
闿意  11:19:17
类似DVB中的TOT和TDT一样，进行网络层的时钟同步
孙悟空  11:19:25
拯救流媒体世界，就看你呢winlin
winlin  11:19:34
去，
北京-赵文杰  11:19:53
@winlin 我老想做这个了，世纪鼎点做到了
凯  11:20:04
根据系统时间来切， 多后直播机推二路流上来，然后在系统中缓冲时间越小越好
闿意  11:20:19
好多服务器都跟GPS连接的，可以做到这点，到MS级
winlin  11:20:21
鼎点做的是编码器，
凯  11:20:20
或者，让 SRS 转发一路流到其它机器
北京-赵文杰  11:20:26
世纪鼎点的wowza 做的HLS HDS热备非常好
孙悟空  11:20:31
powza
孙悟空  11:20:33
不是wowza
孙悟空  11:20:34
哈哈

**Comment by winlinvip** [comment]
杰哥，你在SRS3中做吧，我干不动了，就靠你了。

**Comment by winlinvip** [comment]
也就是能选一种方法或者算法，根据atc和关键帧信息，选择什么时候开始切片，这个热备方案是可以商用的。否则过度依赖编码器，是不好用的

**Comment by wenjiegit** [comment]
嗯，放在3.0中，想干这个都2年了！

**Comment by winlinvip** [comment]
我去，这么看重这个功能！

**Comment by winlinvip** [comment]
我想这个热备有以下几个关键点：
1. 必须使用atc，并且将包的时间戳转换成绝对时间
2. 必须进行gop分析，也就是缓存几个gop之后再进行切片。
3. 必须在任意时间点都知道如何切片，也就是任何时候都不能依赖于上下文。
4. 切片的文件名必须用绝对时间生成，且可以猜测到。

**Comment by winlinvip** [comment]
也就是说，两台机器只有一个在切片到存储，然后挂了之后另外一个才切片？
悟空，你这种在切换时会有点间隙，不过简单很多，那么点瑕疵无所谓的。
悟空提的用冷备做热备，个人觉得是最高的方案！

**Comment by winlinvip** [comment]
这个我已经在外围实现，发现在服务器上实现的代价太大了，不合适。
实际上悟空的方案还可以改进，去掉对存储的依赖:
1. 两个服务器切相似的HLS流就可以，每个SRS加一个GO服务器做的前端web服务器，作为热备。
2. 使用GO写这个前端web服务器，hook SRS的on_hls事件，可以把所有推上来的流做热备，
3. 每个GO服务器，在收到on_hls事件后，把本地SRS的ts片存储到local目录。
4. 每个GO服务器，把热备的GO服务器的ts片，存储到remote目录。
5. 两个GO服务器，使用vote选举算法，选举出来的master存储到main目录，这个目录提供服务。
也就是说，某一个时刻，只有local或者remote可用，因为main是local或者remote的一个副本。

**Comment by winlinvip** [comment]
有需要可以联系我们，这个作为系统产品比较合适，而不是做到流媒体。
所以我们是把这个HLS热备做到我们商业产品中的，有需要联系：http://www.chnvideo.com

**Comment by winlinvip** [comment]
https://github.com/winlinvip/simple-rtmp-server/commit/dbcd7d883b9a34b6a9f7fcb298a5ab3cf68b8daf
添加了一个脚本，检测两个hls流是否互为热备。

**Comment by winlinvip** [comment]
检测两个HLS流是否为热备：
```
./research/hls/check_hls_backup.sh http://ossrs.net:1984/hls/live/livestream/live.m3u8 http://ossrs.net:1996/hls/live/livestream/live.m3u8
```

下面两个HLS流是热备的，由两个SRS切出来的：
 http://ossrs.net:1984/hls/live/livestream/live.m3u8 
http://ossrs.net:1996/hls/live/livestream/live.m3u8

但是这两个流本身不是热备（同步过之后才是热备）：
 http://ossrs.net:1984/hls_local/live/livestream/live.m3u8 
http://ossrs.net:1996/hls_local/live/livestream/live.m3u8
