### ISSUE TITLE
consumer 不释放

### ISSUE THREAD

**Issue by tufang14** [winlinvip/simple-rtmp-server#352]
SrsStreamCache::cycle() 中有个consumer 好像永远不会释放，这样对于edge来说永远不会on_all_client_stop，导致SrsEdgeIngester一直不会停，如果客户端请求一些不存在的流，那edge就会一直像origin重试这些不存在的流，这样的流多了，不仅edge会有压力，origin也会有压力吧，要怎么解决？

**Comment by winlinvip** [comment]
SrsStreamCache是给http aac、mp3用的，目的就是为了多cache，因此不能断开连接。
http flv、ts不会用到这个，没有问题，另外可以配置关闭这个feature。
