### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [winlinvip/simple-rtmp-server#354]
I would like to point out that identifiers like "[`__SRS_JSON_USE_NXJSON`](https://github.com/winlinvip/simple-rtmp-server/blob/99a455fdeb1b60d280f3632e12c455b27ff1551d/trunk/src/app/srs_app_json.hpp#L37)" and "[`__SRS_XSTR`](https://github.com/winlinvip/simple-rtmp-server/blob/c991c2c92c32b44addc8df07f8a6f2900cec0499/trunk/src/core/srs_core.hpp#L58)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by winlinvip** [comment]
Can you please give me a solution?

**Comment by winlinvip** [comment]
Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.

I see, I will remove the __, use _ instead.

**Comment by winlinvip** [comment]
The C++ Standard, [reserved.names], specifies the following rules regarding reserved names [ISO/IEC 14882-2014]:
A translation unit that includes a standard library header shall not #define or #undef names declared in any standard library header.
A translation unit shall not #define or #undef names lexically identical to keywords, to the identifiers listed in Table 3, or to the attribute-tokens described in 7.6.
Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.
Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.
Each name declared as an object with external linkage in a header is reserved to the implementation to designate that library object with external linkage, both in namespace std and in the global namespace.
Each global function signature declared with external linkage in a header is reserved to the implementation to designate that function signature with external linkage.
Each name from the Standard C library declared with external linkage is reserved to the implementation for use as a name with extern "C" linkage, both in namespace std and in the global namespace.
Each function signature from the Standard C library declared with external linkage is reserved to the implementation for use as a function signature with both extern "C" and extern "C++" linkage, or as a name of namespace scope in the global namespace.
For each type T from the Standard C library, the types ::T and std::T are reserved to the implementation and, when defined, ::T shall be identical to std::T.
Literal suffix identifiers that do not start with an underscore are reserved for future standardization.
The identifiers and attribute names mentioned above are: override, final, alignas, carries_dependency, deprecated, and noreturn.
No other identifiers are reserved. Declaring or defining an identifier in a context in which it is reserved results in undefined behavior. Do not declare or define a reserved identifier.

**Comment by elfring** [comment]
Thanks for your source code improvement.
