### ISSUE TITLE
feathers request (discussed  on  QQ group ),remark

### ISSUE THREAD

**Issue by xxxman2008** [winlinvip/simple-rtmp-server#355]
request HLS Based URL configuration item:
(增加 HLS 播放列表 默认/基础URL配置项：)
     This feature applies to HLS playlists. It can let download the playlist and play it locally since it contains full references to child playlists or fragments.

request add new function to  “Listen”  configuration item:

    current “Listen” key does not support  listen on diffrent address .please make it possiable.
    expect format  :   " listen   [address]:[port]"  ,address as ip address ,value "0.0.0.0"  for listen on all ip addresses on host machine.

**Comment by winlinvip** [comment]
The hls_entry_prefix, or the base url, supported in SRS2.
The listen address see #149
