### ISSUE TITLE
port change

### ISSUE THREAD

**Issue by sellapia** [winlinvip/simple-rtmp-server#357]
You are using the SRS well.
First, thank
rtmp tell us how you can change the default listen port of 1935 think I appreciated.

Version that you are using 1.0r3 release (1.0.30) of http://ossrs.net/ version is in use by installing and raspberry pi2 and "/ usr / local / srs / conf" file in the conf files from 1935 to 1936 the changes I've changed in 1936 does not accept the RTMP streams.

Let me know if this solution going to receive the same IP for multiple streams.

**Comment by winlinvip** [comment]
You can change the config file:
```
listen              1935;
```
