### ISSUE TITLE
能否增加像nginx的access.log的记录日志信息

### ISSUE THREAD

**Issue by han4235** [winlinvip/simple-rtmp-server#359]
能支持像nginx-rtmp的日志记录信息吗？
log_format rtmp '$remote_addr\t$unix_time\$bytes_sent\t$command\t$tcurl\t$name\t$pageurl\t$flashver\t$session_time'

**Comment by winlinvip** [comment]
SRS提供更先进的日志：https://github.com/winlinvip/simple-rtmp-server/wiki/v1_CN_SrsLog
若需要使用nginx那种日志，需要自己开发了。

**Comment by winlinvip** [comment]
还是以后考虑是否支持这种日志吧。
