### ISSUE TITLE
可否缩小仓库大小？

### ISSUE THREAD

**Issue by m13253** [winlinvip/simple-rtmp-server#361]
`git clone` 的时候提示仓库有近百兆，这对生产环境布署造成了困难。

我发现仓库中存放了大量的视频文件和 PDF 文档，能否将它们分开到别的地方，让需要的人单独去取它吗？

（其实即使移走之后，因为 git 历史的原因还是占用那么多空间的，但是下载的时候可以用 `--depth` 来不下载历史）

谢谢。

**Comment by winlinvip** [comment]
用以下命令可以快速搞定这个问题：
```
git clone https://git.oschina.net/winlinvip/srs.oschina.git && cd srs.oschina &&
git remote set-url origin https://github.com/winlinvip/simple-rtmp-server.git
```
耗时`0m40.788s`可见只有40秒就下载下来了，是阿里云的cdn提供的服务。
其他国内镜像，参考：https://github.com/winlinvip/simple-rtmp-server/tree/develop#mirrors

**Comment by winlinvip** [comment]
https://github.com/winlinvip/simple-rtmp-server/wiki/v1_CN_Git#fast-checkout

**Comment by m13253** [comment]
原来你的解决方法是：

1. 换个 6M 以上的宽带

2. 用国内镜像

不过我现在看了wiki理解了你把大文件包含进去的目的。
谢谢你的解释和这个出色的软件！

**Comment by winlinvip** [comment]
推荐你用nginx-rtmp，有骨气的就这辈子都别用SRS。

**Comment by m13253** [comment]
> 不过我现在看了wiki理解了你把大文件包含进去的目的。
> 谢谢你的解释和这个出色的软件！

我刚刚的意思是赞扬啊……抱歉让你误会了……

**Comment by winlinvip** [comment]
我去，原来这话不是反话，我说不至于明月照沟渠～
