### ISSUE TITLE
[功能修改：]  SRS不对HLS作自动删除，交由用户设定系统策略或者脚本进行删除

### ISSUE THREAD

**Issue by xxxman2008** [winlinvip/simple-rtmp-server#366]
目前的情况下，SRS 会自动删除 当前Index 之前的 所有HLS切片文件。在用户网速较低，并结合目前网页播放器的现状，会引起用户在观看视频的时候 时间跳跃。 

另外，自动删除切片对某些需要 备份切片的 功能需求也是一个阻碍。

因此，建议 SRS 不要直接管理HLS切片，而是交由用户根据自己的需要，对切片文件进行管理。

**Comment by winlinvip** [comment]
增加一个`hls_cleanup  off;`的配置项，默认开启清理，关掉后就不删除片。
