### ISSUE TITLE
[ 功能修改 ] 建议引入  exec （执行本地可执行程序）功能。

### ISSUE THREAD

**Issue by xxxman2008** [winlinvip/simple-rtmp-server#367]
目前 SRS内置 的 ffmpeg 的 参数配置功能，可以保留，建议增加 exec 配置，让用户可自由执行 本地可执行程序。增加灵活性。

**Comment by winlinvip** [comment]
这个放在3.0之后考虑。能否举出例子来，说明exec你必须要用的？
