### ISSUE TITLE
[功能增强] 添加 systemcmd 脚本

### ISSUE THREAD

**Issue by xxxman2008** [winlinvip/simple-rtmp-server#368]
由于目前 CentOS 已经升级到7 .并开始采用 systemcmd 。虽然目前的 启动方法 能继续使用，但是systemcmd 一统天下已经是大势。建议在可能的情况下增加 systemcmd 脚本。

**Comment by winlinvip** [comment]
哈哈，升级到一统天下了都。
能否提供systemcmd的写法？把 trunk/etc/init.d/srs 翻译成这个systemcmd吧，
我看看能否加进去。
