### ISSUE TITLE
增加 HLS 额外窗口

### ISSUE THREAD

**Issue by wenjiegit** [winlinvip/simple-rtmp-server#370]
建议增加HLS额外窗口，目的是防止某个用户网络抖动时，片被删除的问题。
建议取名:
hls_extra_window_size  

例如
```
hls {
   # xxxx;
   hls_extra_window_size  20;
   # xxxx;
}
```

意思说，20s的数据是延时删除的。

**Comment by winlinvip** [comment]
这个确实是一个值得考虑的功能。
考虑到hls的配置已经一长遛了，也不是非做不可的功能，还是先推到3.0吧

**Comment by xxxman2008** [comment]
其实 配置一个 是否删除的 指令就 好了嘛。要么删除，要么不删除。在繁忙的服务器上，还能节省 磁盘I/O

**Comment by winlinvip** [comment]
雷妈，是否删除的指令`hls_cleanup`已经支持了，这个功能是另外的应用领域，不冲突。

**Comment by xxxman2008** [comment]
SRS 版本 ：2.0.157

实际配置情况：
原始流 ，推送到 VHOST 的  livepkgr （app）  ，然后  设置只对 livepkgr  转码  ，转码后的流回推   VHOST 的  hls （app）。

实际测试情况：
配置 hls_cleanup     off;
原始流（也就是  app 为 livepkgr 的流），产生的 HLS 切片，按照设定的，没有删除。

转码后 回推自身的 流 ，（也就是  app 为 hls 的流）  ，HLS切片继续被删除，不受 hls_cleanup    参数影响。

下面是 配置文件节选：

vhost *******.com {

    #是否启用HLS切片
    hls {
        enabled         on;
        hls_path        /tmp/rtmpAndhls;
        hls_fragment    5;
        hls_window      30;
        hls_on_error    ignore;
        hls_cleanup     off;

        hls_entry_prefix http://********/hls;
    }
    #针对 livepkgr 进行转码.
    transcode livepkgr {
        enabled     on;
        ffmpeg      /usr/local/ffmpeg/ffmpeg;
        engine 512k {
            # whether the engine is enabled
            # default: off.
            enabled         on;
            vfilter {
                # -v quiet
                v           quiet;
            }
            vcodec          libx264;
            # video bitrate, in kbps
            vbitrate        400;
            vwidth          720;
            vheight         400;
            vthreads        8;
            vprofile        main;
            vpreset         superfast;
            vfps            25;
            vparams {
                maxrate         512k
                bufsize         250M
                tune            zerolatency;
                movflags        faststart;
                g               12;
            }
            acodec          an;
            aparams {
            }
            oformat         flv;
            # output stream. variables:
            output          rtmp://127.0.0.1:[port]/hls?vhost=[vhost]/[stream]_[engine];
        }
    }
}

**Comment by winlinvip** [comment]
fixed。

**Comment by xxxman2008** [comment]
2.0.159 版本 ，CentOS 7  未能测试成功，昨天晚上6点左右下载的 github 代码编译的。
