### ISSUE TITLE
remote模式无法支持多级stream

### ISSUE THREAD

**Issue by hillbun** [winlinvip/simple-rtmp-server#373]
vhost tv.unbtv.tv {
    mode            remote;
    origin          tv.unbtv.tv:1935;
}

源地址是 
rtmp://tv.unbtv.tv:1935/app_2/_definst_/ls_1.stream

当访问下面地址
rtmp://x.x.x.x/app_2?vhost=tv.unbtv.tv/_definst_/ls_1.stream

时，日志提示：

vhost tv.unbtv.tv_definst_ not found. ret=2014(Resource temporarily unavailable)

**Comment by winlinvip** [comment]
这个是多级stream，而不是多级app。
这个没有计划支持的。

**Comment by winlinvip** [comment]
一般多级stream都能支持单级stream，没有想到需要多级stream的情况。
可以多级app+vhost，足够应付所有的应用了。

**Comment by hillbun** [comment]
那我需要如何实现reomote方式拉
rtmp://tv.unbtv.tv:1935/app_2/definst/ls_1.stream

**Comment by winlinvip** [comment]
源站换个服务器呗。或者，如果流比较少，可以用ingest。

**Comment by hillbun** [comment]
从效率和稳定性来说，是不是ingest比remote模式要差？  还是一样？

**Comment by winlinvip** [comment]
稳定性要看ffmpeg的了，应该是要差些，不过还行。
edge的逻辑比ffmpeg少很多，要好一些。
