### ISSUE TITLE
How to protect publish other than using IP address deny/allow?

### ISSUE THREAD

**Issue by j3dd4h** [winlinvip/simple-rtmp-server#377]
In the wiki mentioned that publish authentication is not supported.
Is there a way to protect publish other than using IP address deny/allow ?

**Comment by xxxman2008** [comment]
in configuration file ，there ‘s  

    #HTTP callback setting ."space key " is  required  for  multi callback-url 
    http_hooks {
        enabled         off;
        on_connect      callbackURL1   callbackURL2 callbackURL3;
        on_close       callbackURL1   callbackURL2 callbackURL3;
        on_publish      callbackURL1   callbackURL2 callbackURL3;
        on_unpublish   callbackURL1   callbackURL2 callbackURL3;
        on_play         callbackURL1   callbackURL2 callbackURL3;
        on_stop        callbackURL1   callbackURL2 callbackURL3;
        on_dvr          callbackURL1   callbackURL2 callbackURL3;
    }
you may  use it in  VHOST section.

check " HTTP CallBack "  for  detail.
