### ISSUE TITLE
配置文件支持include引用其他文件吗？

### ISSUE THREAD

**Issue by hillbun** [winlinvip/simple-rtmp-server#378]
配置文件支持include引用其他文件吗？
另外，有没办法检查配置配置文件的正确性？ 类似apachectl configtest

**Comment by xxxman2008** [comment]
include  指令 ，不支持

检查配置文件的正确性 ---  有 

少问，多动手try 。这些问题你自己都可以 实验出来的。

**Comment by winlinvip** [comment]
雷妈说得有理。
