### ISSUE TITLE
rpi2 build error

### ISSUE THREAD

**Issue by sellapia** [winlinvip/simple-rtmp-server#379]
The SRS is conducting tests in rpi2.
RTMP stream of base operating normally very good.

Push the MPEG-TS over UDP Or Push RTSP Protocol progress while using the video you will be asked to test a problem.

"./configure -pi --with-stream-caster" during the build "error: invalid option --with-stream-caster" is built out stops.

the same error and proceed using scripts / package.sh I appear

Please help.

**Comment by winlinvip** [comment]
The stream caster is experiment of SRS 2.0, and SRS2 is dev status.
So, I will fix it in SRS2 or SRS3.
