### ISSUE TITLE
截图：snapshot the rtmp stream

### ISSUE THREAD

**Issue by winlinvip** [winlinvip/simple-rtmp-server#382]
截图我会在SRS3支持，遇到关键帧时，就保存为一个flv文件，然后调用ffmpeg截图。
可以配置路径，还有截图时间间隔之类。这样就可以实现类似图片预览流的功能。

**Comment by backylee** [comment]
ffmpeg可以对rtmp流进行抓图吧，不用再保存为一次flv文件，产生一次磁盘操作。

**Comment by winlinvip** [comment]
流截图的等待时间比较长，需要等到关键帧。
直接把关键帧写入文件，然后再转码成图片，这个只是多一次文件写入而已，速度上会快很多。

**Comment by calabashdad** [comment]
截图可以直接对最新的ts文件进行截图，调用ffmpeg，我已经实现此功能。
