### ISSUE TITLE
可否对srs DVR录制功能segment模式做点增强

### ISSUE THREAD

**Issue by backylee** [winlinvip/simple-rtmp-server#385]
SRS版本号：srs2.0.160
OS:Centos6

srs的dvr有两种模式：一种是按session，一个session存入一个文件；一种是按segment，假设一个片30s一个文件。
segment模式目前srs的行为是，如果流停止一段时间后再推送，会继续在之前的文件里append直到该文件长度达到30s才会关闭，然后生成新的文件。这种模式有一定的应用场景，回放这个文件的时候，录像的时间会跳跃，就是append导致的。

现在我碰到这种场景，按需录像，有需要的时候流才会推送给srs，如果没需要就关闭推流。事后需要查阅的时候，能够很快找到想看的时间点的视频。

能否对segment改进下，建议增加个参数控制是否append。如果不append的时候，流断开就把文件关闭，即使该文件没达到指定的长度。

**Comment by winlinvip** [comment]
可以在segment模式中，加入一个控制参数：`reap_unpublish on;`，在unpublish时切割文件。
这个功能还没有实现，可以在2.0做。

**Comment by winlinvip** [comment]
另外，如果时间戳不跳跃，是否就能接受append？

**Comment by walkermi** [comment]
我觉得@backylee 想要的就是“在unpublish时切割文件”，而不管是否到了segment指定的时间。

直播的时候，unpublish后，恢复推流，时间戳肯定跳跃了。
文件转推过来的，如果时间戳不跳跃，我倒是能接受继续append。

不过，还是那句话，我不是专业人士。意见只是我个人看法。

**Comment by backylee** [comment]
推流断开后立刻继续publish的时候，如果断开时间很短，假设3s以内，继续在之前的文件里append也不错，可能实现上复杂点。如果时间长点，还是关闭文件，另外新生成文件，因为可以根据文件名里的时间信息快速索引。避免视频里时间戳跳跃，而无法定位想看的时间点。
