### ISSUE TITLE
[bug]srs develop coredump

### ISSUE THREAD

**Issue by peckjerry** [winlinvip/simple-rtmp-server#394]
develop branch coredump info as follows:

0x0000003932ce0b2b in writev () from /lib64/libc.so.6
(gdb) bt
#0  0x0000003932ce0b2b in writev () from /lib64/libc.so.6
#1  0x00000000005319f9 in st_writev (fd=0x970e90, iov=0xb6fe40, iov_size=52, timeout=30000000) at io.c:593
#2  0x00000000004788c2 in SrsStSocket::writev (this=0x920110, iov=0xb6fe40, iov_size=52, nwrite=0x0) at src/app/srs_app_st_socket.cpp:163
#3  0x0000000000435102 in SrsProtocol::do_iovs_send (this=0xb6ed60, iovs=0xb6fe40, size=52) at src/protocol/srs_rtmp_stack.cpp:1020
#4  0x000000000043502e in SrsProtocol::do_send_messages (this=0xb6ed60, msgs=0x9b1d70, nb_msgs=25) at src/protocol/srs_rtmp_stack.cpp:948
#5  0x00000000004369d2 in SrsProtocol::send_and_free_messages (this=0xb6ed60, msgs=0x9b1d70, nb_msgs=25, stream_id=1) at src/protocol/srs_rtmp_stack.cpp:1320
#6  0x000000000044c070 in SrsRtmpServer::send_and_free_messages (this=0x9231c0, msgs=0x9b1d70, nb_msgs=25, stream_id=1) at src/protocol/srs_rtmp_sdk.cpp:812
#7  0x000000000047438d in SrsRtmpConn::do_playing (this=0xb97cc0, source=0x90abc0, consumer=0x13bdcd0, trd=0x7ffff421d910) at src/app/srs_app_rtmp_conn.cpp:745
#8  0x000000000047390b in SrsRtmpConn::playing (this=0xb97cc0, source=0x90abc0) at src/app/srs_app_rtmp_conn.cpp:595
#9  0x0000000000472d61 in SrsRtmpConn::stream_service_cycle (this=0xb97cc0) at src/app/srs_app_rtmp_conn.cpp:461
#10 0x0000000000471d97 in SrsRtmpConn::service_cycle (this=0xb97cc0) at src/app/srs_app_rtmp_conn.cpp:324
#11 0x000000000047131a in SrsRtmpConn::do_cycle (this=0xb97cc0) at src/app/srs_app_rtmp_conn.cpp:197
#12 0x000000000046f3be in SrsConnection::cycle (this=0xb97d20) at src/app/srs_app_conn.cpp:63
#13 0x00000000004aabf3 in SrsThread::thread_cycle (this=0x957cb0) at src/app/srs_app_thread.cpp:187
#14 0x00000000004aade3 in SrsThread::thread_fun (arg=0x957cb0) at src/app/srs_app_thread.cpp:225
#15 0x000000000052f55a in _st_thread_main () at sched.c:327
#16 0x000000000052fcf4 in st_thread_create (start=0x7ffff7fd6c50, arg=0x1f7fd6b80, joinable=0, stk_size=5456689) at sched.c:591
#17 0x000000000052eed7 in _st_vp_schedule () at sched.c:127
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by winlinvip** [comment]
请切换几个frame，看看是哪个指针破坏了：
```
f 2
p *this
f 3
p *this
f 7 
p *this
```
