### ISSUE TITLE
wiki对与HLS的说明有误。

### ISSUE THREAD

**Issue by daozhao** [winlinvip/simple-rtmp-server#395]
在文档说明中 https://github.com/winlinvip/simple-rtmp-server/wiki/v1_CN_RTMP.PK.HTTP 对于HLS说明有误，HLS应该是apple的开放协议。不是adobe的。
```
HLS

HLS是adobe的开放标准，在Android3?以上也原生支持.

```

**Comment by winlinvip** [comment]
没错，是apple的，我已经fix了。
