### ISSUE TITLE
HTTP hooks for hstrs(http-flv)

### ISSUE THREAD

**Issue by astralink** [winlinvip/simple-rtmp-server#396]
first thanks for good work srs it save a lot of program was i use to get needed results .
also thanks for good hstrs
i hope to add this option 
-1
save_last_key_frame     on;
max_gop_size 250;
#this opiton to save last key frame and overwrite with last one so make stream work faster than normal waiting for getting key like m3u8 and make max limit mem this may make delay and use more mem.
2- add hstrs and hls hook so we can auth it like rtmp by CherryPy or other http call 
post host and other variable to hook ..
thanks

**Comment by winlinvip** [comment]
1. The save last key frame for http-flv or rtmp, already supported by gop cache, you can enable by `gop_cache on;`, read more about the gop cache.
2. The hooks for hstrs not support yet, I will support in SRS3.
