### ISSUE TITLE
HLS纯音频VLC无法播放

### ISSUE THREAD

**Issue by winlinvip** [winlinvip/simple-rtmp-server#40]
ffmpeg -re -i outputn.flv -acodec copy -vn -f flv "rtmp://127.0.0.1:1935/live/stream"
文件内音频编码为aac。
推送到srs后切成hls，用vlc播放无法播放。

**Comment by winlinvip** [comment]
fixed，HLS已经重写了。

**Comment by niuxsh** [comment]
你好，我也碰到了这个问题，我写的PMT里没有视频信息，就只有音频，ffplay能播放，VLC不能播放，请问你是怎么解决的？

**Comment by niuxsh** [comment]
srs_2.0对纯音频的流进行切片时，总是写同一个ts文件，没有持续生成新ts文件，并且用VLC不能播放切片；srs_1.0切出的纯音频文件用VLC还是不能播放，PMT里有video信息。

**Comment by winlinvip** [comment]
请在这里提交bug：https://github.com/simple-rtmp-server/srs/issues/new

**Comment by winlinvip** [comment]
https://github.com/simple-rtmp-server/srs/issues/478#issuecomment-139939122
