### ISSUE TITLE
srs.librtmp无法对接FMS/RED5

### ISSUE THREAD

**Issue by backylee** [winlinvip/simple-rtmp-server#400]
srs.librtmp是librtmp的改版，测试srs.librtm对接srs和nginx-rtmp都没问题。测试对接FMS和RED5失败，文杰的ble用的是librtmp，对接FMS没问题。保持librtmp的兼容性，对srs.librtmp有很大意义。

**Comment by winlinvip** [comment]
@see https://github.com/simple-rtmp-server/srs/issues/456

以后请在这里提交问题：https://github.com/simple-rtmp-server/srs/issues/new
