### ISSUE TITLE
flash publisher source code

### ISSUE THREAD

**Issue by pandababa** [winlinvip/simple-rtmp-server#402]
I use flash as3 to create a live stream publisher (camera and microphone).
After connected successfully and started to publish stream, the connection is closed automatically.

Is there anything special I need to do in as3?

is there any flash source code of the flash publisher in demo (srs_publisher/release/srs_publisher.swf?_version=1.23)?

Thank you!

**Comment by winlinvip** [comment]
Yep, here: https://github.com/simple-rtmp-server/srs/tree/2.0release/trunk/research/players/srs_publisher/src/srs_publisher.as

BTW: Please file issues at https://github.com/simple-rtmp-server/srs/issues/new
