### ISSUE TITLE
HLS ram-storage overflow

### ISSUE THREAD

**Issue by icevl** [winlinvip/simple-rtmp-server#411]
I use ram storage for HLS (SRS 3.0) and find some trouble.
It seem to ram not free when old HLS part has been cleaned.
Thanks for you work. SRS 3.0 is great!

**Comment by winlinvip** [comment]
It's a bug, I will fix it.

**Comment by winlinvip** [comment]
Please file bug at: https://github.com/simple-rtmp-server/srs/issues/new
