### ISSUE TITLE
播放hls流的时候没有调用on_play的httpcallback

### ISSUE THREAD

**Issue by polyzz** [winlinvip/simple-rtmp-server#52]
SRS在播放HLS的视频流的时候没有调用on_play的httpcallback，这样就无法统计准确的统计流媒体的播放次数和时长

希望在播放HLS流的时候，可以和RTMP的流一样调用on_play和on_stop的api，同时提供stream_type类型方便系统统计

**Comment by winlinvip** [comment]
推迟到3.0.
HLS如果只是源站，这个认证还可以做，如果涉及到cdn边缘回源，这个问题就复杂了。因此2.0这个问题还解决不了，需要往后延。
