### ISSUE TITLE
ingest 无法实现多码流输出

### ISSUE THREAD

**Issue by dean-river** [winlinvip/simple-rtmp-server#58]
我想实现 让ingest也像推流时transcode 那样配置多个engine 可以输出多种码流。
但在配置文件中：transcode对ingest的流好像不起作用。而直接在ingest中多配置一个engine也没有效果。ingest的原流可以正常播放。我不知道是不是自己的配置文件写的不对，请帮忙看看。以下是两种配置文件的内容
<pre>
1******************************
# use ffmpeg to ingest file/stream/device to SRS
# @see https://github.com/winlinvip/simple-rtmp-server/wiki/SampleIngest
# @see full.conf for detail config.
 
listen              1935;
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine{
                enabled    off;
                output     rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
     }
     transcode{
                enabled       on
                ffmepg      ./objs/ffmpeg/bin/ffmpeg;
                engine big {
                    enabled         on;
                    vfilter {
                    }
                    vcodec          libx264;
                    vbitrate        500;
                    vfps            25;
                    vwidth          1024;
                    vheight         768;
                    vthreads        12;
                    vprofile        main;
                    vpreset         medium;
                    vparams {
                    }
                    acodec          libaacplus;
                    abitrate        70;
                    asample_rate    44100;
                    achannels       2;
                    aparams {
                    }
                    output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream_[engine];
                }
        }
 
        forward         127.0.0.1:19350;
}

2****************************

# use ffmpeg to ingest file/stream/device to SRS
# @see https://github.com/winlinvip/simple-rtmp-server/wiki/SampleIngest
# @see full.conf for detail config.
 
listen              1935;
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine{
                enabled    off;
                output     rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
        engine big {
                    enabled         on;
                    vfilter {
                    }
                    vcodec          libx264;
                    vbitrate        500;
                    vfps            25;
                    vwidth          1024;
                    vheight         768;
                    vthreads        12;
                    vprofile        main;
                    vpreset         medium;
                    vparams {
                    }
                    acodec          libaacplus;
                    abitrate        70;
                    asample_rate    44100;
                    achannels       2;
                    aparams {
                    }
                    output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream_[engine];
                }
     }
 
        forward         127.0.0.1:19350;
}

</pre>

**Comment by winlinvip** [comment]
推迟到3.0，目前大部分使用的是输出一个。

**Comment by winlinvip** [comment]
另外，可以输出一个后，再使用transcode转码一次。

**Comment by winlinvip** [comment]
所以觉得这个ingest以后只会支持一个输出，而不是支持多个engine；以后会做这个限制，不允许配置多个输出。
